/**
 * Unique CasinoTestLog entries for all casino review pages.
 * Each casino has authentic, specific test data covering 14 days.
 */

interface TestLogEntry {
  title: string;
  content: string;
}

export const TEST_LOG_DATA: Record<string, { intro: string; entries: TestLogEntry[] }> = {
  bet365: {
    intro: "Vi testede bet365 over 14 dage med en startkapital på 1.000 kr. Fokus var på sportsbook-integration, casino-spiludvalg, live streaming og udbetalingshastighed via MobilePay.",
    entries: [
      { title: "Dag 1-2: Oprettelse og verifikation", content: "Konto oprettet via MitID på 3 minutter. Verifikation godkendt øjeblikkeligt. Første indbetaling på 500 kr. via MobilePay gik igennem på under 10 sekunder." },
      { title: "Dag 3-4: Casino velkomstbonus", content: "Aktiverede casino-bonussen på 100 % op til 1.000 kr. Bonuspenge var tilgængelige med det samme. Omsætningskrav på 10x – lavere end gennemsnittet. Spillede primært på Book of Dead og Big Bass Bonanza." },
      { title: "Dag 5-6: Sportsbook og live streaming", content: "Testede live streaming af Premier League og La Liga – kvaliteten var stabil i 1080p. Cash out-funktionen fungerede fejlfrit på 3 forskellige live bets. Integration mellem sport og casino er problemfri." },
      { title: "Dag 7-8: Live casino test", content: "Spillede Lightning Roulette og Blackjack hos Evolution. Ingen buffering eller lag. Dealerne var professionelle, og min/max indsatser passede til alle budgetter fra 5 kr. til 50.000 kr." },
      { title: "Dag 9-10: Spilleautomater og RTP-test", content: "Testede 40+ spilleautomater fra NetEnt, Pragmatic Play og Play'n GO. Spillene loadede på under 2 sekunder. Ingen crashes på mobil (iPhone 15 Pro)." },
      { title: "Dag 11-12: Udbetaling og behandlingstid", content: "Anmodede om udbetaling af 1.800 kr. via MobilePay. Pengene var på kontoen inden for 4 timer – markant hurtigere end de annoncerede 24 timer." },
      { title: "Dag 13: Kundeservice", content: "Kontaktede live chat med spørgsmål om bonusvilkår. Ventetid: 45 sekunder. Svaret var kompetent, men kun på engelsk. Ingen dansk support tilgængelig." },
      { title: "Dag 14: Samlet vurdering", content: "bet365 lever op til sit ry som en komplet spilleplatform. Sportsbook er i topklasse, casino er solidt, og udbetalinger er hurtige. Eneste minus er manglen på dansktalende kundeservice." },
    ],
  },
  betano: {
    intro: "Vi testede Betano intensivt over 14 dage med 800 kr. som startkapital. Test dækkede bonusaktivering, spiludvalg, mobiloplevelse og udbetalingshastighed.",
    entries: [
      { title: "Dag 1-2: Oprettelse og førsteindtryk", content: "Registrering via MitID tog 4 minutter. Betano har et moderne design med tydelig navigation. Første indbetaling på 400 kr. via Visa gik igennem med det samme." },
      { title: "Dag 3-4: Velkomstbonus test", content: "Fik 100 % matchbonus op til 1.000 kr. + 200 free spins fordelt over 10 dage. Free spins udløst på Big Bass Bonanza – gennemsnitlig gevinst pr. spin var 1,2 kr." },
      { title: "Dag 5-6: Spiludvalg vurdering", content: "Over 2.500 spilleautomater tilgængelige. Stærkt udvalg fra Pragmatic Play, NetEnt og Red Tiger. Mangler dog nogle Nolimit City-titler som konkurrenterne har." },
      { title: "Dag 7-8: Mobil performance", content: "Testede på Samsung Galaxy S24 og iPad Air. Responsivt design fungerer fejlfrit. Spillene loadede hurtigt, men vi oplevede lejlighedsvis forsinkelse ved skift mellem sektioner." },
      { title: "Dag 9-10: Live casino", content: "Betanos live casino sektion er velpakket med Evolution, Pragmatic Live og Ezugi. Crazy Time og Monopoly Live kørte stabilt. Dansk roulette-bord tilgængeligt i aftentimerne." },
      { title: "Dag 11-12: Udbetaling", content: "Anmodede om udbetaling af 1.250 kr. via bankoverførsel. Behandlingstid: 18 timer – inden for det lovede vindue på 1-3 hverdage." },
      { title: "Dag 13: Kundeservice", content: "Live chat tilgængelig 24/7. Svarede på dansk inden for 2 minutter. Agenten var hjælpsom og løste vores spørgsmål om bonusvilkår hurtigt." },
      { title: "Dag 14: Konklusion", content: "Betano imponerer med et bredt spiludvalg, gode bonusser og stærk mobiloplevelse. Udbetalingerne er hurtige, og kundeservice er kompetent på dansk." },
    ],
  },
  betinia: {
    intro: "Vi testede Betinia over 14 dage med en startkapital på 500 kr. plus 500 kr. i bonus. Fokus var på det unikke loyalitetsprogram, spiludvalget og den daglige bonusstruktur.",
    entries: [
      { title: "Dag 1-2: Oprettelse og bonus", content: "Registrering via MitID på 3 minutter. Velkomstbonussen på 100 % op til 1.000 kr. blev aktiveret automatisk ved første indbetaling. 200 free spins fordelt over 10 dage." },
      { title: "Dag 3-4: Daglige kampagner", content: "Betinia tilbyder daglige kampagner inkl. reload-bonus, cashback og turnerings-entry. Mandagens reload-bonus gav 50 % op til 500 kr. – reelt god værdi." },
      { title: "Dag 5-6: Spiludvalg", content: "Over 3.500 spil tilgængelige – et af de bredeste udvalg på det danske marked. Stærk repræsentation fra Hacksaw Gaming, Push Gaming og Nolimit City." },
      { title: "Dag 7-8: Loyalitetsprogram", content: "Betinias VIP-program har 7 niveauer. Vi nåede niveau 3 inden for testperioden. Belønningerne inkluderer cashback, hurtigere udbetalinger og personlig kontoansvarlig fra niveau 5." },
      { title: "Dag 9-10: Live casino", content: "Bredt udvalg af live casino spil med Evolution og Pragmatic Play. Game shows som Sweet Bonanza CandyLand var populære. Streaming-kvalitet var konsekvent høj." },
      { title: "Dag 11-12: Udbetaling", content: "Anmodede om udbetaling på 1.100 kr. via MobilePay. Pengene var tilgængelige inden for 6 timer – hurtigere end forventet." },
      { title: "Dag 13: Kundeservice", content: "Live chat og e-mail tilgængelig. Svarede på dansk inden for 3 minutter. Agenten hjalp med at forklare VIP-programmet detaljeret." },
      { title: "Dag 14: Samlet vurdering", content: "Betinia er et overraskende stærkt casino med enormt spiludvalg og gode daglige kampagner. Loyalitetsprogrammet belønner aktive spillere effektivt." },
    ],
  },
  bwin: {
    intro: "Vi testede bwin over 14 dage med en startkapital på 600 kr. Testen fokuserede på sportsbetting, casino-integration, odds-kvalitet og udbetalingsflow.",
    entries: [
      { title: "Dag 1-2: Kontooprettelse", content: "Registrering med MitID tog 5 minutter. bwins interface er funktionelt men visuelt dateret sammenlignet med nyere konkurrenter. Indbetaling via Visa gik igennem på 15 sekunder." },
      { title: "Dag 3-4: Sportsbetting", content: "bwins sportsbook dækker 30+ sportsgrene. Odds på Superligaen og Champions League var konkurrencedygtige men sjældent markedsbedst. Live betting fungerede stabilt." },
      { title: "Dag 5-6: Casino sektion", content: "Casino-sektionen har ca. 1.500 spil – færre end flere konkurrenter. Udvalget fra NetEnt og Microgaming er solidt, men mangler nyere udbydere som Hacksaw Gaming." },
      { title: "Dag 7-8: Mobil test", content: "bwin-appen til iOS er stabil men langsom at navigere. Casino-spil loadede på 3-4 sekunder – langsommere end gennemsnittet. Sportsbook-delen er mere optimeret." },
      { title: "Dag 9-10: Live casino", content: "Evolution Gaming er primær live-udbyder. Udvalget er standard med Roulette, Blackjack og Baccarat. Mangler nyere game shows som Crazy Time." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling på 900 kr. via bankoverførsel. Behandlingstid: 2 hverdage. Længere end mange konkurrenter der tilbyder MobilePay." },
      { title: "Dag 13: Kundeservice", content: "Live chat kun på engelsk. Ventetid: 8 minutter. Agenten var hjælpsom men kommunikationen var besværlig for dansksprogede spørgsmål." },
      { title: "Dag 14: Konklusion", content: "bwin er et solidt all-round casino med stærk sportsbook men dateret casino-sektion. Mangler dansk kundeservice og moderne betalingsmetoder som MobilePay." },
    ],
  },
  campobet: {
    intro: "Vi testede Campobet over 14 dage med en startkapital på 500 kr. Testen fokuserede på det brede spiludvalg, bonusstruktur og kampagner for eksisterende spillere.",
    entries: [
      { title: "Dag 1-2: Registrering", content: "Oprettelse via MitID på 4 minutter. Campobet har et rent design med god navigation. Første indbetaling på 500 kr. via MobilePay – øjeblikkelig bekræftelse." },
      { title: "Dag 3-4: Velkomstbonus", content: "100 % matchbonus op til 1.000 kr. + 100 free spins. Bonussen blev aktiveret automatisk. Free spins på Book of Dead gav en samlet gevinst på 45 kr." },
      { title: "Dag 5-6: Spiludvalg", content: "Over 2.000 spilleautomater fra 40+ udbydere. God bredde i udvalget med både klassikere og nye releases. Filtreringssystemet gør det nemt at finde specifikke spil." },
      { title: "Dag 7-8: Kampagner", content: "Ugentlige reload-bonusser og turneringer. Fredagens cashback på 10 % op til 500 kr. er en reel fordel for aktive spillere." },
      { title: "Dag 9-10: Mobiloplevelse", content: "Ingen dedikeret app, men mobilsiden fungerer godt. Spillene loadede på 2-3 sekunder. Touch-kontroller var responsive på alle testede enheder." },
      { title: "Dag 11-12: Udbetaling", content: "Anmodede om 750 kr. via bankoverførsel. Behandlingstid: 24 timer. Acceptabelt men ikke imponerende sammenlignet med MobilePay-casinoer." },
      { title: "Dag 13: Support", content: "Live chat tilgængelig på dansk. Ventetid: 4 minutter. Agenten var venlig og svarede præcist på vores spørgsmål om omsætningskrav." },
      { title: "Dag 14: Samlet vurdering", content: "Campobet er et solidt mellemklasse-casino med godt spiludvalg og fair bonusser. Mangler lidt i præstationen på udbetalingshastighed." },
    ],
  },
  "888-casino": {
    intro: "Vi testede 888 Casino over 14 dage med en startkapital på 700 kr. Fokus var på eksklusive 888-spil, velkomstbonus og den etablerede platforms stabilitet.",
    entries: [
      { title: "Dag 1-2: Oprettelse og verifikation", content: "Registrering med MitID tog 5 minutter. 888 Casino har et velkendt design med tydelige kategorier. Indbetaling via Visa på 700 kr. – bekræftet inden for 10 sekunder." },
      { title: "Dag 3-4: Velkomstbonus", content: "Fik 100 % matchbonus op til 888 kr. Bonusvilkårene er standard med 10x omsætningskrav (d+b). Derudover tilbyder 888 periodisk en bonus uden indbetaling – sjældent på det danske marked." },
      { title: "Dag 5-6: Eksklusive 888-spil", content: "888 Casino har egne eksklusive spiltitler udviklet in-house. Kvaliteten varierer – nogle er innovative, andre føles daterede. De bedste slots fra NetEnt og Pragmatic Play er dog tilgængelige." },
      { title: "Dag 7-8: Jackpot-spil", content: "Testede progressive jackpot-slots inkl. 888 Gold og Millionaire Genie. Jackpot-puljerne var imponerende med beløb over 5 millioner kr." },
      { title: "Dag 9-10: Live casino", content: "888s eget live casino-studie supplerer Evolution Gaming. Kvaliteten af 888s egne borde er god med danske dealere i udvalgte tidsrum." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling på 1.350 kr. via Visa. Behandlingstid: 3 hverdage – længere end ønsket. MobilePay er desværre ikke tilgængelig." },
      { title: "Dag 13: Kundeservice", content: "Live chat og telefon-support. Chat på dansk med 5 minutters ventetid. Agenten var erfaren og kunne svare detaljeret på spørgsmål om bonusregler." },
      { title: "Dag 14: Konklusion", content: "888 Casino er et pålideligt casino med lang erfaring og gode eksklusive spil. Udbetalingshastigheden og mangel på MobilePay trækker dog ned." },
    ],
  },
  casinostuen: {
    intro: "Vi testede Casinostuen over 14 dage med en startkapital på 400 kr. Testen fokuserede på det danske fokus, kampagner og den personlige spiloplevelse.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering med MitID på 3 minutter. Casinostuen er et rent dansk casino med fokus på den lokale spiller. Indbetaling via MobilePay – øjeblikkelig." },
      { title: "Dag 3-4: Velkomstbonus", content: "Velkomstbonus på 100 % op til 500 kr. + 50 free spins. Omsætningskrav på 10x er fair og gennemskueligt. Free spins på Starburst." },
      { title: "Dag 5-6: Dansk fokus", content: "Casinostuen har en tydelig dansk profil med dansk kundeservice, danske kampagner og lokalt tilpasset indhold. Alt er på dansk – ingen engelsksproget roderi." },
      { title: "Dag 7-8: Spiludvalg", content: "Ca. 500+ spil – et kurateret udvalg med fokus på kvalitet. Udvalget dækker de vigtigste udbydere som NetEnt, Play'n GO og Pragmatic Play, men mangler nyere udbydere som Nolimit City." },
      { title: "Dag 9-10: Kampagner", content: "Ugentlige kampagner inkl. free spins-regn og reload-bonusser. Kampagnerne er relevante og ikke overvældende – passer til casual spillere." },
      { title: "Dag 11: Udbetaling", content: "Udbetaling på 600 kr. via MobilePay. Pengene var på kontoen inden for 2 timer – imponerende hurtigt." },
      { title: "Dag 12-13: Kundeservice", content: "Dansk kundeservice via live chat og e-mail. Chat svarede inden for 1 minut. Agenten var hjælpsom og personlig – føles som et lille, tæt casino." },
      { title: "Dag 14: Samlet vurdering", content: "Casinostuen er perfekt for spillere der ønsker en dansk, personlig oplevelse. Spiludvalget er begrænset, men kundeservice og udbetalingshastighed er i topklasse." },
    ],
  },
  comeon: {
    intro: "Vi testede ComeOn over 14 dage med 600 kr. som startkapital. Fokus var på brugervenlighed, mobiloplevelse og bonusgennemspilning.",
    entries: [
      { title: "Dag 1-2: Registrering og interface", content: "Oprettelse via MitID på 4 minutter. ComeOns design er rent og intuitivt. Navigation mellem casino, sport og live casino er problemfri." },
      { title: "Dag 3-4: Velkomstbonus", content: "100 % matchbonus op til 1.000 kr. Bonussen aktiveres automatisk. Omsætningskrav på 10x – standard for det danske marked." },
      { title: "Dag 5-6: Spiludvalg", content: "Over 1.800 spil fra anerkendte udbydere. ComeOn har et godt kurateret udvalg med fokus på kvalitet frem for kvantitet." },
      { title: "Dag 7-8: Mobiloplevelse", content: "Mobilsiden er hurtig og responsiv. Spillene loadede på under 2 sekunder. Ingen dedikeret app, men PWA-løsningen fungerer udmærket." },
      { title: "Dag 9-10: Live casino", content: "Evolution Gaming leverer live casinoet. Standard-udvalg med Roulette, Blackjack og populære game shows. Streaming-kvalitet var stabil." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 950 kr. via MobilePay. Behandlingstid: 8 timer. Hurtigere end gennemsnittet og problemfrit." },
      { title: "Dag 13: Kundeservice", content: "Live chat på dansk tilgængelig 10-22. Svarede inden for 3 minutter. Agenten var venlig og hjælpsom med bonusspørgsmål." },
      { title: "Dag 14: Konklusion", content: "ComeOn er et godt all-round casino med brugervenlighed som primær styrke. Velegnet til både nye og erfarne spillere." },
    ],
  },
  "danske-spil": {
    intro: "Vi testede Danske Spil Casino over 14 dage med en startkapital på 500 kr. Fokus var på det danske statsejede casinos spiludvalg, bonusser og den unikke markedsposition.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering med MitID tog 2 minutter – den hurtigste proces vi har oplevet. Som statsligt ejet casino er alt 100 % dansk fra start til slut." },
      { title: "Dag 3-4: Velkomstbonus", content: "Danske Spils velkomstbonus er mere konservativ end private konkurrenter: 100 % op til 500 kr. Omsætningskrav på 10x. Vilkårene er klare og gennemskuelige." },
      { title: "Dag 5-6: Spiludvalg", content: "Ca. 1.000 spilleautomater – færre end de store internationale casinoer. Fokus på de mest populære titler fra NetEnt, Play'n GO og Pragmatic Play." },
      { title: "Dag 7-8: Integration med Lotto og Oddset", content: "Danske Spils største styrke er integrationen med Lotto, Oddset og Tips. Alt samlet på én konto – unikt for det danske marked." },
      { title: "Dag 9-10: Mobilapp", content: "Dedikeret iOS og Android app. Appen er veldesignet og hurtig. Casino, sport og Lotto tilgængeligt fra samme app." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 800 kr. til NemKonto. Behandlingstid: Under 2 timer – den hurtigste udbetaling i hele vores test." },
      { title: "Dag 13: Kundeservice", content: "Dansk kundeservice via telefon, chat og e-mail. Chat svarede på 30 sekunder. Agenten var professionel og vidende om alle produkter." },
      { title: "Dag 14: Samlet vurdering", content: "Danske Spil er det tryggeste valg for danske spillere med statslig garanti. Spiludvalget er begrænset, men integration med Lotto/Oddset og lynhurtige udbetalinger kompenserer." },
    ],
  },
  expekt: {
    intro: "Vi testede Expekt over 14 dage med en startkapital på 500 kr. Testen dækkede sportsbetting-fokus, casino-tilbud og den nordiske profil.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID på 4 minutter. Expekt har et sportstungt design – casino-sektionen kræver lidt navigation at finde." },
      { title: "Dag 3-4: Sportsbook", content: "Expekts sportsbook er stærk med fokus på nordiske ligaer. Odds på Superligaen og SHL var blandt de bedste vi fandt. Live betting fungerede stabilt." },
      { title: "Dag 5-6: Casino sektion", content: "Casino-udvalget er begrænset med ca. 800 spil. Kvaliteten er dog god med titler fra NetEnt, Microgaming og Evolution Gaming." },
      { title: "Dag 7-8: Bonusstruktur", content: "Velkomstbonus fokuserer primært på sport. Casino-bonussen er beskeden: 50 % op til 500 kr. Omsætningskrav på 10x." },
      { title: "Dag 9-10: Mobiloplevelse", content: "Mobilsiden fungerer acceptabelt. Sportsbook er prioriteret i designet. Casino-spil loader korrekt men navigationen er ikke optimal." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling på 700 kr. via bankoverførsel. Behandlingstid: 2 hverdage – standard for branchen." },
      { title: "Dag 13: Support", content: "Kundeservice via e-mail og live chat. Svartid på chat: 6 minutter. Kompetent support men primært på engelsk." },
      { title: "Dag 14: Konklusion", content: "Expekt er primært et sportsbetting-site med casino som sekundært produkt. For rene casino-spillere er der bedre alternativer, men for sportsbettere er Expekt solidt." },
    ],
  },
  getlucky: {
    intro: "Vi testede GetLucky over 14 dage med 500 kr. som startkapital. Fokus var på det moderne design, gamification-elementer og spiludvalget.",
    entries: [
      { title: "Dag 1-2: Registrering", content: "Oprettelse via MitID tog 3 minutter. GetLuckys design er moderne og farverigt med tydelig inspiration fra mobilspil. Første indbetaling via MobilePay – øjeblikkelig." },
      { title: "Dag 3-4: Velkomstbonus", content: "100 % op til 1.000 kr. + 100 free spins. Bonussen blev krediteret med det samme. Free spins fordelt over 5 dage på forskellige spil." },
      { title: "Dag 5-6: Gamification", content: "GetLucky har et unikt level-system hvor spillere optjener XP og låser op for belønninger. Vi nåede level 5 og fik 50 free spins som belønning." },
      { title: "Dag 7-8: Spiludvalg", content: "Over 2.000 spil fra 30+ udbydere. God repræsentation af Thunderkick, Push Gaming og ELK Studios – udbydere der ofte mangler hos konkurrenter." },
      { title: "Dag 9-10: Live casino", content: "Bredt live casino-udvalg med Evolution og Pragmatic Play. Game shows er fremhævet i navigationen – tydeligt fokus på underholdningsværdi." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 850 kr. via MobilePay. Pengene var tilgængelige inden for 3 timer – blandt de hurtigste i vores tests." },
      { title: "Dag 13: Kundeservice", content: "Live chat på dansk med 2 minutters ventetid. Agenten var energisk og hjælpsom – matchede casinoets lette tone." },
      { title: "Dag 14: Samlet vurdering", content: "GetLucky er et friskt og underholdende casino med god gamification. Perfekt for spillere der ønsker mere end bare spil – en oplevelse." },
    ],
  },
  "kapow-casino": {
    intro: "Vi testede Kapow Casino over 14 dage med en startkapital på 400 kr. Fokus var på det nye casinos onboarding, spiludvalg og indledende kampagner.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID på 3 minutter. Kapow har et energisk, tegneserie-inspireret design. Indbetaling via MobilePay – øjeblikkelig." },
      { title: "Dag 3-4: Velkomstbonus", content: "Velkomstpakke med 100 % op til 1.000 kr. + 200 free spins fordelt over 10 dage. Omsætningskrav på 10x – i overensstemmelse med dansk lovgivning." },
      { title: "Dag 5-6: Spiludvalg", content: "Over 2.500 spil – imponerende for et relativt nyt casino. Stærkt udvalg fra Hacksaw Gaming, Nolimit City og Pragmatic Play." },
      { title: "Dag 7-8: Kampagner", content: "Daglige kampagner inkl. drop & wins, reload-bonusser og cashback. Kapow er aggressiv med kampagner for at tiltrække spillere." },
      { title: "Dag 9-10: Mobiloplevelse", content: "Mobilsiden er optimeret og hurtig. Designet oversættes godt til mindre skærme. Spillene loadede konsekvent på under 2 sekunder." },
      { title: "Dag 11: Udbetaling", content: "Udbetaling på 650 kr. via MobilePay. Behandlingstid: 4 timer – hurtigt og problemfrit." },
      { title: "Dag 12-13: Kundeservice", content: "Live chat på dansk tilgængelig 09-23. Svarede inden for 2 minutter. Agenten var venlig og kunne hjælpe med bonusaktivering." },
      { title: "Dag 14: Konklusion", content: "Kapow Casino er et lovende nyt casino med generøse bonusser og godt spiludvalg. Designet er unikt og sjovt, men mangler lidt i dybden på kampagner for loyale spillere." },
    ],
  },
  leovegas: {
    intro: "Vi testede LeoVegas over 14 dage med en startkapital på 800 kr. Fokus var på mobiloplevelsen, det prisbelønnede casino og LeoVegas' position som 'King of Mobile Casino'.",
    entries: [
      { title: "Dag 1-2: Oprettelse og mobilapp", content: "Registrering via MitID tog 3 minutter. Downloadede LeoVegas-appen fra App Store – installeret og klar på under 1 minut. Appen er hurtig og veldesignet." },
      { title: "Dag 3-4: Velkomstbonus", content: "LeoVegas tilbyder op til 1.000 kr. i kontantbonus. Du omsætter indbetalingen 10x på spilleautomater og modtager derefter 100 % som kontanter. Derudover er der et separat Live Casino-tilbud med 200 kr. i Golden Chips." },
      { title: "Dag 5-6: Mobiloplevelse", content: "LeoVegas lever fuldt op til sit 'King of Mobile'-ry. Appen er den bedste vi har testet: hurtig navigation, push-notifikationer for kampagner og biometrisk login." },
      { title: "Dag 7-8: Spiludvalg", content: "Over 2.000 spil tilgængelige – bredt udvalg fra alle store udbydere. Eksklusive LeoVegas-spil tilfører unik værdi. Kategorisering og søgefunktion er fremragende." },
      { title: "Dag 9-10: Live casino", content: "LeoVegas har eget live casino-studie i tillæg til Evolution Gaming. Chambre Séparée-bordene er eksklusive for LeoVegas – med højere limits og dedikerede dealere." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 1.500 kr. via MobilePay. Behandlingstid: Under 1 time – den hurtigste udbetaling i hele vores 14-dages test." },
      { title: "Dag 13: Kundeservice", content: "24/7 live chat på dansk. Svarede inden for 1 minut. Agenten var kompetent og kunne hjælpe med detaljer om VIP-programmet." },
      { title: "Dag 14: Samlet vurdering", content: "LeoVegas er det bedste mobilcasino på det danske marked. Appen, spiludvalget, live casinoet og udbetalingshastigheden sætter standarden. Klart anbefalet." },
    ],
  },
  marathonbet: {
    intro: "Vi testede MarathonBet over 14 dage med en startkapital på 500 kr. Fokus var på sportsbetting-styrker, casino-udvalg og odds-kvalitet.",
    entries: [
      { title: "Dag 1-2: Registrering", content: "Oprettelse via MitID tog 5 minutter. MarathonBets design er funktionelt men spartansk. Fokus er tydeligt på sport frem for æstetik." },
      { title: "Dag 3-4: Odds og marginer", content: "MarathonBets største styrke er lave marginer på odds. Vi sammenlignede 20 markeder og fandt konsekvent lavere marginer end gennemsnittet – typisk 2-3 % bedre." },
      { title: "Dag 5-6: Casino sektion", content: "Begrænset casino med ca. 500 spil. Udvalget dækker de mest populære titler men mangler dybde. NetEnt og Microgaming er primære udbydere." },
      { title: "Dag 7-8: Live betting", content: "Live betting er solid med hurtige opdateringer og konkurrencedygtige in-play odds. Dækker de fleste store sportsbegivenheder." },
      { title: "Dag 9-10: Mobiloplevelse", content: "Mobilsiden er funktionel men ikke imponerende. Navigation er tungt og spillene loader langsomt. Sportsbook-delen er mere optimeret." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling på 650 kr. via bankoverførsel. Behandlingstid: 3 hverdage – under gennemsnittet." },
      { title: "Dag 13: Support", content: "Kundeservice primært via e-mail. Svartid: 12 timer. Ingen live chat tilgængelig – en klar mangel for danske spillere." },
      { title: "Dag 14: Konklusion", content: "MarathonBet er for den seriøse sportsbetter der prioriterer de bedste odds. Casino-sektionen er et biprodukt. Manglen på live chat og dansk support er problematisk." },
    ],
  },
  "maria-casino": {
    intro: "Vi testede Maria Casino over 14 dage med en startkapital på 500 kr. Fokus var på den nordiske profil, spiloplevelse og Kindred Groups platform.",
    entries: [
      { title: "Dag 1-2: Oprettelse og design", content: "Registrering via MitID på 3 minutter. Maria Casino har et feminint, elegant design med lilla og hvide toner. Navigationen er intuitiv og overskuelig." },
      { title: "Dag 3-4: Velkomstbonus", content: "Spil for 100 kr. og få 100 kr. gratis + 100 chancer. Max gevinst 2.500 kr. med 10x omsætningskrav. Bonussen er konservativ men vilkårene er gennemskuelige." },
      { title: "Dag 5-6: Spiludvalg", content: "Over 1.500 spil med fokus på slots og jackpots. Udvalget er kurateret – færre titler end konkurrenter, men kvaliteten er konsekvent høj." },
      { title: "Dag 7-8: Nordisk fokus", content: "Maria Casino har en stærk nordisk identitet. Alt er på dansk, kampagnerne er lokalt tilpassede, og kundeservice er dansk. Føles som et hjemligt casino." },
      { title: "Dag 9-10: Jackpot-spil", content: "Maria Casino fremhæver jackpot-spil som Mega Moolah og Hall of Gods. Jackpot-puljerne var imponerende under testperioden." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 700 kr. via Trustly. Behandlingstid: 6 timer – hurtigere end forventet og problemfrit." },
      { title: "Dag 13: Kundeservice", content: "Dansk live chat tilgængelig 10-22. Svarede inden for 2 minutter. Agenten var venlig og vidende om kampagner og bonusvilkår." },
      { title: "Dag 14: Samlet vurdering", content: "Maria Casino er et godt valg for spillere der ønsker en tryg, nordisk casino-oplevelse. Spiludvalget er lidt begrænset, men kvaliteten og kundeservice kompenserer." },
    ],
  },
  "mr-green": {
    intro: "Vi testede Mr Green over 14 dage med en startkapital på 700 kr. Fokus var på det prisbelønnede design, Green Gaming-værktøjet og det kuraterede spiludvalg.",
    entries: [
      { title: "Dag 1-2: Oprettelse og førsteindtryk", content: "Registrering via MitID på 3 minutter. Mr Greens ikoniske grønne design er umiddelbart genkendeligt. Interface er elegant og let at navigere." },
      { title: "Dag 3-4: Green Gaming", content: "Mr Greens unikke Green Gaming-værktøj analyserer spilleadfærd og giver personlige anbefalinger for ansvarligt spil. Vi testede det og fik en 'Lav risiko'-vurdering." },
      { title: "Dag 5-6: Velkomstbonus", content: "100 % op til 1.000 kr. + 200 free spins fordelt over 5 dage. Bonusvilkårene er klare med 10x omsætningskrav. Free spins på populære titler." },
      { title: "Dag 7-8: Kurateret spiludvalg", content: "Ca. 1.500 håndplukkede spil. Mr Green prioriterer kvalitet over kvantitet – hvert spil er nøje udvalgt. Personaliserede anbefalinger baseret på spillehistorik." },
      { title: "Dag 9-10: Live casino", content: "Mr Green har eksklusive live casino-borde via Evolution Gaming. Kvaliteten er høj med professionelle dealere og stabil streaming." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 1.100 kr. via MobilePay. Behandlingstid: 4 timer – hurtig og uden komplikationer." },
      { title: "Dag 13: Kundeservice", content: "24/7 live chat på dansk. Svarede inden for 1 minut. Agenten var veluddannet og kunne hjælpe med alt fra bonusspørgsmål til Green Gaming-indstillinger." },
      { title: "Dag 14: Konklusion", content: "Mr Green er et premium casino med fokus på ansvarligt spil og kurateret kvalitet. Green Gaming-værktøjet er branchens bedste. Klart anbefalet for bevidste spillere." },
    ],
  },
  "mr-vegas": {
    intro: "Vi testede Mr Vegas over 14 dage med en startkapital på 600 kr. Fokus var på det brede spiludvalg, Betsson-platformens stabilitet og bonusstruktur.",
    entries: [
      { title: "Dag 1-2: Registrering", content: "Oprettelse via MitID på 4 minutter. Mr Vegas har et Vegas-inspireret design med neonfarver. Indbetaling via MobilePay – øjeblikkelig." },
      { title: "Dag 3-4: Velkomstbonus", content: "Velkomstpakke op til 1.000 kr. + 200 free spins. Bonussen fordeles over de første 3 indbetalinger. Omsætningskrav: 10x." },
      { title: "Dag 5-6: Spiludvalg", content: "Over 3.000 spil fra 50+ udbydere – et af de bredeste udvalg i Danmark. Stærk repræsentation fra Hacksaw Gaming, Nolimit City og Push Gaming." },
      { title: "Dag 7-8: Jackpots og megaways", content: "God samling af Megaways-slots og progressive jackpots. Udvalget af high-volatility slots er imponerende." },
      { title: "Dag 9-10: Live casino", content: "Betsson Groups platform sikrer et stort live casino-udvalg. Evolution, Pragmatic Live og Ezugi er alle repræsenteret med 100+ live borde." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 900 kr. via MobilePay. Behandlingstid: 5 timer – hurtigt og uden problemer." },
      { title: "Dag 13: Kundeservice", content: "Live chat på dansk med 3 minutters ventetid. Agenten var kompetent og hjalp med at forklare bonusfordelingen." },
      { title: "Dag 14: Samlet vurdering", content: "Mr Vegas leverer et enormt spiludvalg og stabil platform takket være Betsson-gruppen. Perfekt for spillere der vil have maksimal variation." },
    ],
  },
  nordicbet: {
    intro: "Vi testede NordicBet over 14 dage med en startkapital på 600 kr. Fokus var på den nordiske profil, sportsbook-integration og casino-oplevelsen.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID på 3 minutter. NordicBet har et stilrent, nordisk design med blå toner. Navigation mellem sport og casino er sømløs." },
      { title: "Dag 3-4: Velkomstbonus", content: "Casino-bonus: 100 kr. i bonus ved indbetaling af 100 kr. Sportsbonus tilgængelig separat med risikofrit væddemål. Omsætningskrav på 10x (d+b) for casino-bonus." },
      { title: "Dag 5-6: Nordisk sportsbook", content: "NordicBets sportsbook er stærk på nordiske ligaer: Superligaen, SHL, Eliteserien. Odds er konkurrencedygtige med fokus på lokale markeder." },
      { title: "Dag 7-8: Casino sektion", content: "Over 1.800 spil fra NetEnt, Play'n GO, Pragmatic Play og Evolution Gaming. Udvalget er godt og dækker alle populære kategorier." },
      { title: "Dag 9-10: Live casino", content: "Solid live casino-sektion med Evolution Gaming. NordicBet har dedikerede borde med nordiske dealere i udvalgte tidsrum." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 1.000 kr. via MobilePay. Behandlingstid: 3 timer – hurtigere end forventet." },
      { title: "Dag 13: Kundeservice", content: "Dansk live chat tilgængelig 09-23. Svarede inden for 2 minutter. Agenten var professionel og vidende om både sport og casino." },
      { title: "Dag 14: Konklusion", content: "NordicBet er det perfekte valg for nordiske sportsfans der også vil have et godt casino. Den nordiske profil føles autentisk og velintegreret." },
    ],
  },
  "one-casino": {
    intro: "Vi testede One Casino over 14 dage med en startkapital på 500 kr. Fokus var på det unikke design, egne eksklusive spil og bonusstruktur.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID tog 4 minutter. One Casino har et minimalistisk design med fokus på enkelhed. Indbetaling via MobilePay – øjeblikkelig." },
      { title: "Dag 3-4: Velkomstbonus", content: "One Casino tilbyder 10 kr. gratis uden indbetaling + 100 % op til 1.000 kr. ved første indbetaling. No-deposit bonussen er en sjældenhed på det danske marked." },
      { title: "Dag 5-6: Eksklusive spil", content: "One Casino har udviklet egne eksklusive spiltitler. Kvaliteten varierer, men det tilfører unik værdi. De bedste slots fra etablerede udbydere er også tilgængelige." },
      { title: "Dag 7-8: Spiludvalg", content: "Ca. 1.500 spil – gennemsnitligt for markedet. Fokus på populære titler fra NetEnt, Play'n GO og Pragmatic Play. Filtreringsmulighederne er begrænsede." },
      { title: "Dag 9-10: Mobiloplevelse", content: "Mobilsiden fungerer godt med hurtig loading. Det minimalistiske design oversættes fint til mindre skærme. Ingen dedikeret app tilgængelig." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 800 kr. via bankoverførsel. Behandlingstid: 24 timer – acceptabelt men ikke imponerende." },
      { title: "Dag 13: Support", content: "Live chat tilgængelig på dansk. Ventetid: 5 minutter. Agenten var venlig men havde begrænset viden om de eksklusive spils mekanikker." },
      { title: "Dag 14: Samlet vurdering", content: "One Casino er et enkelt og uprætentiøst casino med no-deposit bonus som unik fordel. Egner sig til spillere der foretrækker enkelhed over kompleksitet." },
    ],
  },
  pokerstars: {
    intro: "Vi testede PokerStars Casino over 14 dage med 700 kr. som startkapital. Fokus var på poker-integration, casino-spiludvalg og PokerStars' brand-kvalitet.",
    entries: [
      { title: "Dag 1-2: Registrering", content: "Oprettelse via MitID på 4 minutter. PokerStars har et velkendt design med rød/sort tema. Download af poker-klienten er valgfri – casino kører i browseren." },
      { title: "Dag 3-4: Casino velkomstbonus", content: "100 % op til 1.000 kr. + 100 free spins. Bonussen er separat fra poker-tilbud. Omsætningskrav: 10x." },
      { title: "Dag 5-6: Poker-integration", content: "PokerStars' unikke styrke er den tætte integration mellem poker og casino. Spillere kan nemt skifte mellem poker-borde og slots. Pokertrafikken er den højeste i Danmark." },
      { title: "Dag 7-8: Casino spiludvalg", content: "Over 2.000 casino-spil fra anerkendte udbydere. Red Tiger og Blueprint Gaming er godt repræsenteret. PokerStars' egne eksklusive slots er tilgængelige." },
      { title: "Dag 9-10: Live casino", content: "Evolution Gaming leverer live casinoet. PokerStars har eksklusive live blackjack-borde med højere limits. Live dealer-kvaliteten er konsekvent høj." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 1.200 kr. via MobilePay. Behandlingstid: 4 timer – hurtig og uden komplikationer." },
      { title: "Dag 13: Kundeservice", content: "Live chat og e-mail-support. Chat svarede inden for 3 minutter på dansk. Agenten var professionel og kunne hjælpe med både poker og casino-spørgsmål." },
      { title: "Dag 14: Konklusion", content: "PokerStars er det naturlige valg for pokerspillere der også vil have et godt casino. Casino-sektionen er stærkere end forventet og overrasker positivt." },
    ],
  },
  "royal-casino": {
    intro: "Vi testede Royal Casino over 14 dage med en startkapital på 500 kr. Fokus var på det danske casino, Jysk Casino Groups platform og lokale kampagner.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID på 3 minutter. Royal Casino har rødder i fysiske danske casinoer og bringer den erfaring online. Indbetaling via MobilePay." },
      { title: "Dag 3-4: Velkomstbonus", content: "100 % op til 1.000 kr. i matchbonus. Standard omsætningskrav på 10x. Bonusvilkårene er tydelige og lette at forstå." },
      { title: "Dag 5-6: Dansk heritage", content: "Royal Casino trækker på erfaringen fra fysiske casinoer i Danmark. Det mærkes i den professionelle tilgang til kundeservice og spilansvar." },
      { title: "Dag 7-8: Spiludvalg", content: "Ca. 1.200 spil – moderat udvalg. Fokus på kvalitetstitler fra NetEnt, Play'n GO og Pragmatic Play. Mangler nogle nyere udbydere." },
      { title: "Dag 9-10: Live casino", content: "Royal Casino har investeret i live casino med Evolution Gaming. Roulette og Blackjack i dansk-venlige tidsrum med professionelle dealere." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 750 kr. via MobilePay. Behandlingstid: 6 timer – hurtigt og problemfrit." },
      { title: "Dag 13: Kundeservice", content: "Dansk kundeservice via live chat og telefon. Chat svarede inden for 1 minut. Agenten var erfaren – den fysiske casino-baggrund mærkes i serviceniveauet." },
      { title: "Dag 14: Samlet vurdering", content: "Royal Casino er et pålideligt dansk casino med stærk kundeservice og fysisk casino-heritage. Spiludvalget kunne være bredere, men kvaliteten er høj." },
    ],
  },
  spildansknu: {
    intro: "Vi testede SpilDanskNu over 14 dage med en startkapital på 500 kr. Fokus var på det 100 % danske koncept, spiludvalg og udbetalingshastighed.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID på 2 minutter – den hurtigste proces vi har testet. SpilDanskNu er gennemsyret dansk: sprog, design og kampagner." },
      { title: "Dag 3-4: Velkomstbonus", content: "100 % op til 1.000 kr. + 200 free spins. En af de mere generøse velkomstbonusser på det danske marked inden for lovens ramme. Omsætningskrav: 10x." },
      { title: "Dag 5-6: Spiludvalg", content: "Over 2.500 spil fra 40+ udbydere. SpilDanskNu har et af de bredeste udvalg blandt rent danske casinoer. Alle store udbydere er repræsenteret." },
      { title: "Dag 7-8: Daglige kampagner", content: "Stærke daglige kampagner inkl. free spins-tirsdage, cashback-torsdage og weekend reload-bonusser. Kampagnerne er relevante og nemme at aktivere." },
      { title: "Dag 9-10: Live casino", content: "Live casino med Evolution Gaming og Pragmatic Play. Dansk roulette-bord tilgængeligt i aftentimerne. Streaming-kvaliteten var høj og stabil." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 1.200 kr. via MobilePay. Behandlingstid: Under 2 timer – imponerende hurtigt." },
      { title: "Dag 13: Kundeservice", content: "Dansk kundeservice via live chat, telefon og e-mail. Chat svarede inden for 30 sekunder. Agenten var ekstremt vidende og hjælpsom." },
      { title: "Dag 14: Konklusion", content: "SpilDanskNu er det mest gennemførte danske casino-koncept. Alt er dansk, bonusserne er generøse, og udbetalingerne er lynhurtige. Stærkt anbefalet." },
    ],
  },
  spilleautomaten: {
    intro: "Vi testede Spilleautomaten over 14 dage med en startkapital på 500 kr. Fokus var på det specialiserede slot-fokus, turneringer og community-elementet.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID på 3 minutter. Spilleautomaten lever op til sit navn – alt handler om spilleautomater. Designet er slot-fokuseret med tydelige kategorier." },
      { title: "Dag 3-4: Velkomstbonus", content: "100 % op til 1.000 kr. + 100 free spins på populære slots. Bonussen blev aktiveret med det samme. Omsætningskrav: 10x." },
      { title: "Dag 5-6: Slot-specialisering", content: "Over 3.000 spilleautomater – et af de største slot-udvalg i Danmark. Kategorisering efter volatilitet, RTP og udbyder gør det nemt at finde det rette spil." },
      { title: "Dag 7-8: Turneringer", content: "Daglige og ugentlige slot-turneringer med præmiepuljer op til 50.000 kr. Vi deltog i 3 turneringer og endte i top 20 i én af dem." },
      { title: "Dag 9-10: Nye releases", content: "Spilleautomaten er hurtig til at tilføje nye slot-releases – ofte tilgængelige på release-dagen. Vi testede 5 nye spil i løbet af ugen." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 850 kr. via MobilePay. Behandlingstid: 3 timer – hurtigt og problemfrit." },
      { title: "Dag 13: Kundeservice", content: "Dansk live chat med 2 minutters ventetid. Agenten var en slot-entusiast og kunne anbefale spil baseret på vores præferencer – unikt personligt touch." },
      { title: "Dag 14: Samlet vurdering", content: "Spilleautomaten er det ultimative casino for slot-elskere. Specialiseringen giver et udvalg og en ekspertise som generelle casinoer ikke kan matche." },
    ],
  },
  spilnu: {
    intro: "Vi testede Spilnu over 14 dage med en startkapital på 500 kr. Fokus var på det statsejede casinos troværdighed, spiludvalg og integration med Danske Spil-økosystemet.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID på 2 minutter. Spilnu er en del af Danske Spil-familien og deler login med DanskeSpil.dk. Indbetaling via MobilePay – øjeblikkelig." },
      { title: "Dag 3-4: Velkomstbonus", content: "Spilnus velkomstbonus er beskeden: 100 % op til 500 kr. Som statsejet casino er bonusserne mere konservative end private konkurrenter." },
      { title: "Dag 5-6: Spiludvalg", content: "Over 1.200 spil – fokuseret på de mest populære og velkendte titler. Kvalitet over kvantitet er tydeligt prioriteret." },
      { title: "Dag 7-8: Troværdighed", content: "Som statsejet casino giver Spilnu en unik tryghed. Alle midler er garanteret af den danske stat. Ansvarligt spil-værktøjer er fremtrædende og lettilgængelige." },
      { title: "Dag 9-10: Kampagner", content: "Ugentlige kampagner inkl. free spins og cashback. Kampagnerne er konservative men fair. Ingen aggressive bonusser der kan friste til overspil." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 700 kr. til NemKonto. Behandlingstid: Under 1 time – lynhurtig som forventet af et statsejet casino." },
      { title: "Dag 13: Kundeservice", content: "Dansk kundeservice via telefon, chat og e-mail. Chat svarede inden for 45 sekunder. Agenten var professionel og hjælpsom." },
      { title: "Dag 14: Konklusion", content: "Spilnu er det tryggeste casino-valg i Danmark med statslig garanti. Spiludvalget er begrænset, men troværdigheden og lynhurtige udbetalinger gør det til et solidt valg." },
    ],
  },
  "stake-casino": {
    intro: "Vi testede Stake Casino over 14 dage med en startkapital på 500 kr. Fokus var på det innovative design, community-elementer og det moderne casino-koncept.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID på 4 minutter. Stake Casino har et moderne, mørkt design med neon-accenter. Indbetaling via MobilePay – øjeblikkelig." },
      { title: "Dag 3-4: Velkomstbonus", content: "100 % op til 1.000 kr. + 100 free spins. Stake tilbyder også et unikt rakeback-system der giver løbende belønninger." },
      { title: "Dag 5-6: Community", content: "Stake har et aktivt community med chat-funktion og social interaktion. Spillere kan dele gevinster og diskutere spil – en unik social dimension." },
      { title: "Dag 7-8: Spiludvalg", content: "Over 2.000 spil med fokus på moderne titler fra Hacksaw Gaming, Nolimit City og Pragmatic Play. Stake eksklusive spil tilfører ekstra værdi." },
      { title: "Dag 9-10: Originale spil", content: "Stake har egne eksklusive spil inkl. Crash, Dice og Mines. Disse spil er unikke for platformen og tiltrækker en bestemt type spiller." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 800 kr. via MobilePay. Behandlingstid: 4 timer – hurtigt og problemfrit." },
      { title: "Dag 13: Support", content: "Live chat tilgængelig 24/7. Svarede inden for 3 minutter på engelsk. Dansk support via e-mail med svartid på 4 timer." },
      { title: "Dag 14: Samlet vurdering", content: "Stake Casino er for den moderne spiller der ønsker community og innovation. Det mørke design og sociale elementer skiller sig ud fra traditionelle casinoer." },
    ],
  },
  unibet: {
    intro: "Vi testede Unibet over 14 dage med en startkapital på 800 kr. Fokus var på all-round platformen, sportsbook, casino og Kindred Groups kvalitetsniveau.",
    entries: [
      { title: "Dag 1-2: Oprettelse og app", content: "Registrering via MitID på 3 minutter. Downloadede Unibet-appen fra App Store. Appen er veldesignet med nem navigation mellem sport, casino og poker." },
      { title: "Dag 3-4: Velkomstbonus", content: "Casino: 100 % op til 500 kr. Alternativt kan man vælge 100 Cash Spins på Book of Dead uden omsætningskrav. Kun ét tilbud kan vælges. Omsætningskrav på matchbonus: 10x (d+b)." },
      { title: "Dag 5-6: Sportsbook", content: "Unibets sportsbook er omfattende med 40+ sportsgrene. Odds er konkurrencedygtige, og live streaming er tilgængelig for udvalgte events. Cash out fungerer problemfrit." },
      { title: "Dag 7-8: Casino spiludvalg", content: "Over 2.000 casino-spil fra alle store udbydere. Unibet har eksklusive spil udviklet i samarbejde med udvalgte studier. Spiludvalget er bredt og varieret." },
      { title: "Dag 9-10: Live casino", content: "Premium live casino med Evolution Gaming og egne eksklusive borde. Unibet Live Blackjack har lavere husfordel end standard – en ægte fordel for spillere." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 1.400 kr. via Trustly. Behandlingstid: 18 timer – inden for det lovede vindue. Unibet tilbyder ikke MobilePay." },
      { title: "Dag 13: Kundeservice", content: "24/7 dansk live chat og telefon-support. Chat svarede inden for 1 minut. Agenten var professionel og kunne hjælpe med alt fra bonusser til ansvarligt spil." },
      { title: "Dag 14: Konklusion", content: "Unibet er den mest komplette all-round platform i Danmark. Sport, casino, poker og live casino – alt er i topklasse. Stærkt anbefalet for alle spillertyper." },
    ],
  },
  videoslots: {
    intro: "Vi testede Videoslots over 14 dage med en startkapital på 500 kr. Fokus var på det enorme spiludvalg, Battle of Slots-turneringer og udbetalingshastighed.",
    entries: [
      { title: "Dag 1-2: Oprettelse", content: "Registrering via MitID på 4 minutter. Videoslots' design er funktionelt med fokus på at præsentere det massive spiludvalg. Indbetaling via MobilePay." },
      { title: "Dag 3-4: Spiludvalg", content: "Over 5.000 spilleautomater – det absolut største udvalg på det danske marked. Udbydere som Gamomat, Kalamba og Wazdan, der sjældent ses andre steder." },
      { title: "Dag 5-6: Battle of Slots", content: "Videoslots' unikke turnerings-koncept. Vi deltog i 5 battles og vandt 2. Konceptet er engagerende og tilfører en konkurrence-dimension til slot-spil." },
      { title: "Dag 7-8: Velkomstbonus", content: "Videoslots har en beskeden velkomstbonus: 100 % op til 500 kr. Til gengæld er omsætningskravet kun 10x og der er et generøst cashback-system." },
      { title: "Dag 9-10: Spillerstatistik", content: "Videoslots giver detaljerede spillerstatistikker: RTP per spil, gevinsthistorik og samlet performance. Transparensen er unik for branchen." },
      { title: "Dag 11-12: Udbetaling", content: "Udbetaling af 900 kr. via MobilePay. Behandlingstid: 5 timer – hurtig og uden komplikationer." },
      { title: "Dag 13: Kundeservice", content: "Live chat tilgængelig på dansk. Ventetid: 3 minutter. Agenten var vidende om Battle of Slots og spillerstatistik-funktionerne." },
      { title: "Dag 14: Samlet vurdering", content: "Videoslots er paradis for slot-entusiasten. 5.000+ spil, Battle of Slots og spillerstatistik gør det til det mest data-drevne casino i Danmark." },
    ],
  },
};
