project_id = "zhpbqqhtgnblaugrqhqi"

[functions.affiliate-redirect]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.delete-admin-user]
verify_jwt = false

[functions.twitch-stream-status]
verify_jwt = false

[functions.twitch-auth]
verify_jwt = false

[functions.twitch-auth-url]
verify_jwt = false

[functions.generate-slot-frame]
verify_jwt = false

[functions.generate-slot-symbol]
verify_jwt = false

[functions.cleanup-unused-images]
verify_jwt = false

[functions.elevenlabs-sfx]
verify_jwt = false

[functions.reset-slot-stats]
verify_jwt = false

[functions.slot-spin]
verify_jwt = false

[functions.twitch-badges]
verify_jwt = false

[functions.admin-manage-points]
verify_jwt = false

[functions.redeem-code]
verify_jwt = false

[functions.verify-slot-password]
verify_jwt = false

[functions.daily-credit-allocation]
verify_jwt = false

[functions.twitch-clip-thumbnail]
verify_jwt = false
