project_id = "zhpbqqhtgnblaugrqhqi"

[functions.affiliate-redirect]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.delete-admin-user]
verify_jwt = false

[functions.twitch-stream-status]
verify_jwt = false

[functions.twitch-auth]
verify_jwt = false

[functions.twitch-auth-url]
verify_jwt = false

[functions.generate-slot-frame]
verify_jwt = false

[functions.generate-slot-symbol]
verify_jwt = false
