import { Link } from "react-router-dom";
import { SEO } from "@/components/SEO";
import { AuthorBio } from "@/components/AuthorBio";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import {
  Users,
  Target,
  Shield,
  CheckCircle2,
  Search,
  RefreshCw,
  Scale,
  Eye,
  Heart,
  Sparkles,
  ArrowRight,
  BookOpen,
  ShieldCheck,
  Gamepad2,
  Quote,
  Clock,
  Tv,
  MessageSquare,
  Trophy,
  Zap,
} from "lucide-react";
import { useSiteSettings } from "@/hooks/useSiteSettings";
import jonasImage from "@/assets/jonas-forfatter.png";
import kevinImage from "@/assets/kevin-forfatter.png";
import { RelatedGuides } from "@/components/RelatedGuides";
import { AuthorMetaBar } from "@/components/AuthorMetaBar";
import omHeroImage from "@/assets/heroes/om-hero.png";

const OmTeamet = () => {
  const { data: siteSettings } = useSiteSettings();
  const heroBackgroundImage = siteSettings?.hero_background;

  const organizationJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": "https://casinoaftaler.dk/#organization",
    name: "Casinoaftaler.dk",
    url: "https://casinoaftaler.dk",
    dateModified: "2026-02-20",
    logo: {
      "@type": "ImageObject",
      url: "https://casinoaftaler.dk/favicon-48x48.png",
      width: 192,
      height: 192,
    },
    description:
      "Casinoaftaler.dk er en dansk casino-guide med fokus på gennemsigtighed, testmetoder og ansvarligt spil.",
    foundingDate: "2021",
    founder: {
      "@type": "Person",
      "@id": "https://casinoaftaler.dk/forfatter/jonas#person",
      name: "Jonas Theill",
      url: "https://casinoaftaler.dk/forfatter/jonas",
    },
    employee: [
      {
        "@type": "Person",
        "@id": "https://casinoaftaler.dk/forfatter/kevin#person",
        name: "Kevin",
        url: "https://casinoaftaler.dk/forfatter/kevin",
        jobTitle: "Casino Streamer & IT-medansvarlig",
      },
    ],
    sameAs: [
      "https://www.youtube.com/@casinoaftaler",
      "https://www.instagram.com/casinoaftaler",
      "https://www.facebook.com/casinoaftaler",
    ],
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer support",
      url: "https://casinoaftaler.dk/kontakt",
      availableLanguage: "Danish",
    },
    publishingPrinciples: "https://casinoaftaler.dk/redaktionel-politik",
    knowsAbout: [
      "Online casino",
      "Casino bonus",
      "Spilleautomater",
      "Casino test",
      "Ansvarligt spil",
    ],
  };

  const websiteJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Casinoaftaler.dk",
    url: "https://casinoaftaler.dk",
    publisher: {
      "@type": "Organization",
      name: "Casinoaftaler.dk",
      url: "https://casinoaftaler.dk",
      logo: {
        "@type": "ImageObject",
        url: "https://zhpbqqhtgnblaugrqhqi.supabase.co/storage/v1/object/public/casino-logos/header-icon.jpg",
        width: 192,
        height: 192,
      },
    },
  };

  // BreadcrumbList is auto-generated by SEO.tsx via buildBreadcrumbListSchema() – no manual injection needed.

  const missionPoints = [
    { icon: CheckCircle2, text: "At give ærlige og opdaterede anmeldelser" },
    { icon: Search, text: "At teste casinoer systematisk" },
    { icon: Heart, text: "At skabe et engageret community" },
    { icon: Sparkles, text: "At kombinere streaming og ekspertise" },
  ];

  const workMethods = [
    {
      icon: Gamepad2,
      title: "Vi tester casinoer praktisk",
      desc: "Hvert casino bliver testet af vores team med registrering, indbetaling og gameplay – ikke kun skrivebordsvurdering.",
    },
    {
      icon: RefreshCw,
      title: "Vi opdaterer bonusser løbende",
      desc: "Bonusser og vilkår ændres ofte. Vi holder vores anmeldelser opdateret, så du altid har de nyeste oplysninger.",
    },
    {
      icon: Search,
      title: "Vi analyserer vilkår",
      desc: "Omsætningskrav, tidsfrister og spilbidrag – vi nedbryder det hele, så du forstår hvad du accepterer.",
    },
    {
      icon: Eye,
      title: "Vi prioriterer gennemsigtighed",
      desc: "Vi fortæller tydeligt hvad der er godt og hvad der ikke er. Ingen skjulte agendaer.",
    },
    {
      icon: Scale,
      title: "Vi adskiller kommercielle samarbejder fra vurdering",
      desc: "Affiliate-partnerskaber påvirker aldrig vores redaktionelle vurderinger eller anbefalinger.",
    },
  ];

  const stats = [
    { icon: Clock, value: "7+", label: "Års samlet streaming-erfaring" },
    { icon: Trophy, value: "30+", label: "Testede danske casinoer" },
    { icon: Tv, value: "7000+", label: "Timers live streaming" },
    { icon: Users, value: "Aktivt", label: "Engageret community" },
  ];

  const trustPoints = [
    "Praktisk test af casinoer",
    "Løbende opdatering af bonusser",
    "Gennemsigtige vurderingskriterier",
    "Klar adskillelse mellem kommercielle samarbejder og redaktionel vurdering",
    "Fokus på ansvarligt spil",
  ];

  return (
    <>
      <SEO
        title="Om teamet bag Casinoaftaler.dk | Streamere & Casinoeksperter"
        description="Mød teamet bag Casinoaftaler.dk. Læs om Jonas og Kevin – casino-streamere og medansvarlige for test, anmeldelser og udvikling."
        jsonLd={[organizationJsonLd, websiteJsonLd]}
      />

      {/* ═══ HERO ═══ */}
      <section
        className="relative overflow-hidden py-16 text-white md:py-28"
        style={{
          backgroundImage: heroBackgroundImage
            ? `linear-gradient(135deg, hsl(260 70% 18% / 0.97), hsl(210 80% 22% / 0.95)), url(${heroBackgroundImage})`
            : "linear-gradient(135deg, hsl(260 70% 18%), hsl(250 60% 15%) 40%, hsl(210 80% 20%))",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <div className="container">
          <div className="mx-auto max-w-4xl text-center">
            <Badge variant="secondary" className="mb-6">
              <Users className="mr-1.5 h-3.5 w-3.5" />
              Om Teamet
            </Badge>
            <h1 className="mb-6 text-4xl font-bold tracking-tight md:text-6xl">
              Teamet bag Casinoaftaler.dk
            </h1>
            <p className="mb-4 text-xl font-semibold text-white/90 md:text-2xl">
              To streamere. Ét fælles mål.
              <br />
              At skabe gennemsigtighed i online casino i Danmark.
            </p>
            <p className="mx-auto max-w-2xl text-base text-white/70 md:text-lg">
              Fra Twitch-streams til systematisk test af casinoer – Casinoaftaler.dk er bygget på
              praktisk erfaring, community og gennemsigtighed.
            </p>

            {/* Profile images side-by-side */}
            <div className="mt-10 flex items-center justify-center gap-6 md:gap-10">
              <Link to="/forfatter/jonas" className="group">
                <div className="mx-auto h-28 w-28 overflow-hidden rounded-2xl border-4 border-white/20 transition-all duration-300 group-hover:border-white/50 group-hover:scale-105 md:h-36 md:w-36">
                  <img src={jonasImage} alt="Jonas – Grundlægger" className="h-full w-full object-cover object-top" loading="eager" />
                </div>
                <p className="mt-2 text-sm font-medium text-white/80">Jonas</p>
              </Link>
              <div className="flex flex-col items-center gap-1">
                <span className="text-3xl font-bold text-white/30">&</span>
              </div>
              <Link to="/forfatter/kevin" className="group">
                <div className="mx-auto h-28 w-28 overflow-hidden rounded-2xl border-4 border-white/20 transition-all duration-300 group-hover:border-white/50 group-hover:scale-105 md:h-36 md:w-36">
                  <img src={kevinImage} alt="Kevin – IT Medansvarlig" className="h-full w-full object-cover object-top" loading="eager" />
                </div>
                <p className="mt-2 text-sm font-medium text-white/80">Kevin</p>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ═══ FRA TWITCH TIL PLATFORM (Storytelling) ═══ */}
      <div className="container py-12 md:py-16">
        <AuthorMetaBar author="jonas" date="17-02-2026" readTime="6 Min." showFactCheck={false} showAffiliateDisclaimer={false} />
        <section className="mb-16">
          <h2 className="mb-6 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <Tv className="h-7 w-7 text-primary" />
            Fra Twitch til Casinoaftaler.dk
          </h2>
          <div className="grid gap-8 md:grid-cols-2">
            <div className="space-y-4">
              <p className="text-muted-foreground leading-relaxed">
                Det hele startede på Twitch. Jonas og Kevin streamede uafhængigt af hinanden, men
                fandt hurtigt fælles interesse for online casino, streaming og det community, der
                voksede op omkring dem.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                De begyndte at gæste hinandens streams, dele erfaringer og diskutere de casinoer,
                de testede. Seerne stillede spørgsmål – og det blev tydeligt, at der manglede et
                sted med ærlig og gennemsigtig information.
              </p>
            </div>
            <div className="space-y-4">
              <p className="text-muted-foreground leading-relaxed">
                Derfra voksede idéen om Casinoaftaler.dk – en platform bygget af streamere med
                praktisk erfaring, for spillere der ønsker gennemsigtighed.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                I dag kombinerer de streaming, systematisk test og community til en samlet
                platform, hvor anmeldelser bygger på reel erfaring – ikke kun skrivebordsvurdering.
              </p>
            </div>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ VORES MISSION ═══ */}
        <section className="mb-16">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <Target className="h-7 w-7 text-primary" />
            Vores mission
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-6">
            Vi arbejder hver dag for at gøre det nemmere og sikrere for danske spillere at navigere
            i verden af online casino. Vores tilgang bygger på reel erfaring, systematisk testning
            og et stærkt fokus på gennemsigtighed.
          </p>
          <div className="grid gap-3 sm:grid-cols-2">
            {missionPoints.map((point) => (
              <div
                key={point.text}
                className="flex items-center gap-3 rounded-lg border border-border bg-card p-4"
              >
                <point.icon className="h-5 w-5 flex-shrink-0 text-primary" />
                <span className="text-sm font-medium">{point.text}</span>
              </div>
            ))}
          </div>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link to="/saadan-tester-vi-casinoer">
              <Button variant="outline" size="sm">
                <ShieldCheck className="mr-1.5 h-4 w-4" />
                Sådan tester vi casinoer
              </Button>
            </Link>
            <Link to="/nye-casinoer">
              <Button variant="outline" size="sm">
                <Sparkles className="mr-1.5 h-4 w-4" />
                Nye Casinoer
              </Button>
            </Link>
            <Link to="/ansvarligt-spil">
              <Button variant="outline" size="sm">
                <Shield className="mr-1.5 h-4 w-4" />
                Ansvarligt Spil
              </Button>
            </Link>
          </div>
        </section>
      </div>

      {/* ═══ CITAT-SEKTION (visuelt adskilt) ═══ */}
      <section
        className="py-16 md:py-20"
        style={{
          background: "linear-gradient(135deg, hsl(260 50% 12%), hsl(230 40% 15%))",
        }}
      >
        <div className="container">
          <h2 className="mb-10 text-center text-3xl font-bold text-white flex items-center justify-center gap-2 md:text-4xl">
            <MessageSquare className="h-7 w-7" />
            Hvad driver os?
          </h2>
          <div className="grid gap-6 md:grid-cols-2">
            <Card className="border-white/10 bg-white/5 backdrop-blur-sm">
              <CardContent className="p-8">
                <Quote className="mb-4 h-8 w-8 text-primary/60" />
                <p className="mb-6 text-xl font-medium leading-relaxed text-white/90 italic">
                  "Streaming handler om energi. Casinoaftaler handler om gennemsigtighed."
                </p>
                <div className="flex items-center gap-3">
                   <div className="h-12 w-12 overflow-hidden rounded-xl border-2 border-primary/30">
                     <img src={jonasImage} alt="Jonas" className="h-full w-full object-cover object-top" />
                  </div>
                  <div>
                    <p className="font-semibold text-white">Jonas</p>
                    <p className="text-sm text-white/60">Grundlægger & Indholdsansvarlig</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-white/10 bg-white/5 backdrop-blur-sm">
              <CardContent className="p-8">
                <Quote className="mb-4 h-8 w-8 text-primary/60" />
                <p className="mb-6 text-xl font-medium leading-relaxed text-white/90 italic">
                  "Vi tester ikke bare casinoer – vi dokumenterer vores vurderinger."
                </p>
                <div className="flex items-center gap-3">
                   <div className="h-12 w-12 overflow-hidden rounded-xl border-2 border-primary/30">
                     <img src={kevinImage} alt="Kevin" className="h-full w-full object-cover object-top" />
                  </div>
                  <div>
                    <p className="font-semibold text-white">Kevin</p>
                    <p className="text-sm text-white/60">Casino-streamer & IT Medansvarlig</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* ═══ TEAMET I TAL ═══ */}
      <div className="container py-12 md:py-16">
        <section className="mb-16">
          <h2 className="mb-8 text-center text-3xl font-bold flex items-center justify-center gap-2 md:text-4xl">
            <Zap className="h-7 w-7 text-primary" />
            Teamet i tal
          </h2>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
            {stats.map((stat) => (
              <Card key={stat.label} className="border-border bg-card text-center">
                <CardContent className="p-6">
                  <stat.icon className="mx-auto mb-3 h-8 w-8 text-primary" />
                  <p className="text-3xl font-bold text-foreground md:text-4xl">{stat.value}</p>
                  <p className="mt-1 text-sm text-muted-foreground">{stat.label}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ MØD TEAMET ═══ */}
        <section className="mb-16">
          <h2 className="mb-6 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <Users className="h-7 w-7 text-primary" />
            Mød teamet
          </h2>
          <div className="grid gap-6 md:grid-cols-2">
            <Card className="border-border bg-card overflow-hidden">
              <CardHeader className="pb-4">
                <div className="flex items-center gap-4">
                  <div className="h-24 w-24 flex-shrink-0 overflow-hidden rounded-2xl border-2 border-primary/30">
                     <img src={jonasImage} alt="Jonas – Grundlægger af Casinoaftaler.dk" className="h-full w-full object-cover object-top" loading="eager" />
                  </div>
                  <div>
                    <CardTitle className="text-xl">Jonas</CardTitle>
                    <div className="mt-1 flex flex-wrap gap-1.5">
                      <Badge variant="secondary" className="text-xs">Grundlægger</Badge>
                      <Badge variant="secondary" className="text-xs">Casino-streamer</Badge>
                      <Badge variant="secondary" className="text-xs">Indholdsansvarlig</Badge>
                    </div>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Grundlægger af Casinoaftaler.dk og casino-streamer med over 4 års erfaring.
                  Ansvarlig for strategi, test og community.
                </p>
                <Link to="/forfatter/jonas">
                  <Button variant="outline" size="sm" className="w-full">
                    Se Jonas' fulde profil
                    <ArrowRight className="ml-1.5 h-4 w-4" />
                  </Button>
                </Link>
              </CardContent>
            </Card>

            <Card className="border-border bg-card overflow-hidden">
              <CardHeader className="pb-4">
                <div className="flex items-center gap-4">
                  <div className="h-24 w-24 flex-shrink-0 overflow-hidden rounded-2xl border-2 border-primary/30">
                     <img src={kevinImage} alt="Kevin – Casino-streamer & IT Medansvarlig" className="h-full w-full object-cover object-top" loading="eager" />
                  </div>
                  <div>
                    <CardTitle className="text-xl">Kevin</CardTitle>
                    <div className="mt-1 flex flex-wrap gap-1.5">
                      <Badge variant="secondary" className="text-xs">Casino-streamer</Badge>
                      <Badge variant="secondary" className="text-xs">IT Medansvarlig</Badge>
                    </div>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  Casino-streamer med 3+ års erfaring og medansvarlig for udvikling og optimering
                  af platformen. Baggrund i professionel content creation og gaming.
                </p>
                <Link to="/forfatter/kevin">
                  <Button variant="outline" size="sm" className="w-full">
                    Se Kevins fulde profil
                    <ArrowRight className="ml-1.5 h-4 w-4" />
                  </Button>
                </Link>
              </CardContent>
            </Card>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ SÅDAN ARBEJDER TEAMET ═══ */}
        <section className="mb-16">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <BookOpen className="h-7 w-7 text-primary" />
            Sådan arbejder teamet
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-8">
            Vores arbejdsproces er designet til at sikre, at alle anmeldelser og anbefalinger
            bygger på reel test og dokumenteret vurdering.
          </p>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {workMethods.map((method) => (
              <Card key={method.title} className="border-border bg-card">
                <CardContent className="p-6">
                  <method.icon className="mb-3 h-6 w-6 text-primary" />
                  <h3 className="mb-2 font-semibold">{method.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{method.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
          <div className="mt-8">
            <Link to="/saadan-tester-vi-casinoer">
              <Button variant="outline" size="sm">
                <ShieldCheck className="mr-1.5 h-4 w-4" />
                Læs mere om vores testmetode
              </Button>
            </Link>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ HVORFOR STOLE PÅ OS ═══ */}
        <section className="mb-16">
          <h2 className="mb-6 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <ShieldCheck className="h-7 w-7 text-primary" />
            Hvorfor stole på Casinoaftaler.dk?
          </h2>
          <div className="rounded-xl border border-border bg-card p-6 md:p-8">
            <div className="space-y-4">
              {trustPoints.map((point) => (
                <div key={point} className="flex items-start gap-3">
                  <CheckCircle2 className="mt-0.5 h-5 w-5 flex-shrink-0 text-primary" />
                  <span className="font-medium">{point}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ VORES TESTMETODE ═══ */}
        <section className="mb-12">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <ShieldCheck className="h-7 w-7 text-primary" />
            Vores testmetode
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Alle anmeldelser på Casinoaftaler.dk bygger på praktisk test udført af vores team. Vi opretter konti,
            indbetaler, spiller og evaluerer hvert casino ud fra faste kriterier – herunder spilsortiment, bonusvilkår,
            kundeservice og udbetalingshastighed.
          </p>
          <Link to="/saadan-tester-vi-casinoer">
            <Button variant="outline" size="sm">
              <ShieldCheck className="mr-1.5 h-4 w-4" />
              Sådan tester vi casinoer
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>

        <Separator className="my-10" />

        {/* ═══ FORRETNINGSMODEL ═══ */}
        <section className="mb-12">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <Scale className="h-7 w-7 text-primary" />
            Forretningsmodel
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Casinoaftaler.dk finansieres gennem affiliate-samarbejder med udvalgte casinoer. Det betyder, at vi
            modtager kommission, når brugere tilmelder sig via vores links. Vores vurderinger og anbefalinger
            er dog altid uafhængige og bygger på faste testkriterier.
          </p>
          <Link to="/forretningsmodel">
            <Button variant="outline" size="sm">
              <Scale className="mr-1.5 h-4 w-4" />
              Læs vores forretningsmodel
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>

        <Separator className="my-10" />

        {/* ═══ REDAKTIONEL POLITIK ═══ */}
        <section className="mb-12">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <BookOpen className="h-7 w-7 text-primary" />
            Redaktionel politik
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Vores redaktionelle politik sikrer en klar adskillelse mellem kommercielt og redaktionelt indhold.
            Alt indhold produceres af vores team, opdateres løbende og følger dokumenterede retningslinjer
            for kvalitet og objektivitet.
          </p>

          <div className="grid gap-4 md:grid-cols-3 mb-6">
            <Card className="border-border bg-card">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 mb-2">
                  <Users className="h-5 w-5 text-primary" />
                  <h3 className="font-semibold text-sm">Rollefordeling</h3>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Jonas står for anmeldelser og guides. Kevin dækker teknik, lovgivning og platformudvikling. De fungerer som hinandens faktatjekkere.
                </p>
              </CardContent>
            </Card>
            <Card className="border-border bg-card">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 mb-2">
                  <CheckCircle2 className="h-5 w-5 text-primary" />
                  <h3 className="font-semibold text-sm">Faktatjek</h3>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Alle artikler gennemgås af en anden redaktør end forfatteren. Bonusvilkår verificeres manuelt mod casinoernes egne sider før publicering.
                </p>
              </CardContent>
            </Card>
            <Card className="border-border bg-card">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 mb-2">
                  <RefreshCw className="h-5 w-5 text-primary" />
                  <h3 className="font-semibold text-sm">Opdateringsfrekvens</h3>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Anmeldelser gennemgås kvartalsvis. Bonusguides opdateres når vilkår ændres. Forældet indhold fjernes eller markeres tydeligt.
                </p>
              </CardContent>
            </Card>
          </div>

          <Link to="/redaktionel-politik">
            <Button variant="outline" size="sm">
              <BookOpen className="mr-1.5 h-4 w-4" />
              Læs den fulde redaktionelle politik
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>

        <Separator className="my-10" />

        {/* ═══ ANSVARLIGT SPIL ═══ */}
        <section className="mb-12">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <Shield className="h-7 w-7 text-primary" />
            Ansvarligt spil
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Vi anbefaler kun licenserede operatører og arbejder aktivt for ansvarligt spil. Alle casinoer på vores platform er tilsluttet ROFUS, og vi opfordrer spillere til at bruge de tilgængelige værktøjer til at sætte grænser for indbetaling, tab og spilletid.
          </p>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Har du brug for hjælp, kan du kontakte <a href="https://www.stopspillet.dk" target="_blank" rel="noopener noreferrer" className="text-primary underline hover:text-primary/80">StopSpillet</a> på telefon 70 22 28 25 (gratis og anonymt) eller udelukke dig selv via <a href="https://www.rofus.nu" target="_blank" rel="noopener noreferrer" className="text-primary underline hover:text-primary/80">ROFUS.nu</a>.
          </p>
          <Link to="/ansvarligt-spil">
            <Button variant="outline" size="sm">
              <Shield className="mr-1.5 h-4 w-4" />
              Læs mere om ansvarligt spil
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>

        <Separator className="my-10" />

        {/* ═══ KONTAKT & IMPRESSUM ═══ */}
        <section className="mb-16">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <MessageSquare className="h-7 w-7 text-primary" />
            Kontakt
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Har du spørgsmål, feedback eller ønsker du at samarbejde med os? Vi hører gerne fra dig.
          </p>
          <Link to="/kontakt">
            <Button variant="outline" size="sm">
              <MessageSquare className="mr-1.5 h-4 w-4" />
              Kontakt os
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>
      </div>

      {/* ═══ CTA SEKTION (visuelt adskilt) ═══ */}
      <section
        className="py-16 md:py-20"
        style={{
          background: "linear-gradient(135deg, hsl(260 60% 15%), hsl(220 50% 18%))",
        }}
      >
        <div className="container text-center">
          <h2 className="mb-4 text-3xl font-bold text-white md:text-4xl">
            Vil du vide mere om vores testmetode?
          </h2>
          <p className="mx-auto mb-8 max-w-xl text-white/70">
            Se hvordan vi arbejder, eller lær vores team bedre at kende via deres personlige profiler.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link to="/saadan-tester-vi-casinoer">
              <Button size="lg" className="font-semibold">
                <ShieldCheck className="mr-2 h-5 w-5" />
                Sådan tester vi casinoer
              </Button>
            </Link>
            <Link to="/forfatter/jonas">
              <Button variant="outline" size="lg" className="border-white/30 text-white bg-white/10 hover:bg-white/20 font-semibold">
                Mød Jonas
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
            <Link to="/forfatter/kevin">
              <Button variant="outline" size="lg" className="border-white/30 text-white bg-white/10 hover:bg-white/20 font-semibold">
                Mød Kevin
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* ═══ RELATEREDE GUIDES ═══ */}
      <div className="container py-12 md:py-16">
        <AuthorBio author="jonas" showCommunity={false} />
        <RelatedGuides currentPath="/om" maxLinks={6} />
      </div>
    </>
  );
};

export default OmTeamet;
