import { Link } from "react-router-dom";
import { SEO } from "@/components/SEO";
import { AuthorBio } from "@/components/AuthorBio";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import {
  Users,
  Target,
  Shield,
  CheckCircle2,
  Search,
  RefreshCw,
  Scale,
  Eye,
  Heart,
  Sparkles,
  ArrowRight,
  BookOpen,
  ShieldCheck,
  Gamepad2,
  Quote,
  Clock,
  Tv,
  MessageSquare,
  Trophy,
  Zap,
  Newspaper,
  Pen,
  FileCheck,
  XCircle,
} from "lucide-react";
import { useSiteSettings } from "@/hooks/useSiteSettings";
import { usePublishedNews } from "@/hooks/useCasinoNews";
import { optimizeStorageImage } from "@/lib/imageOptimization";
import jonasImage from "@/assets/jonas-forfatter.webp";
import kevinImage from "@/assets/kevin-forfatter.webp";
import ajseImage from "@/assets/ajse-avatar.webp";
import { RelatedGuides } from "@/components/RelatedGuides";
import { AuthorMetaBar } from "@/components/AuthorMetaBar";
import omHeroImage from "@/assets/heroes/om-hero.png";

const OmTeamet = () => {
  const { data: siteSettings } = useSiteSettings();
  const { data: latestNewsData } = usePublishedNews(1, 6);
  const heroBackgroundImage = siteSettings?.hero_background;
  const latestArticles = latestNewsData?.articles ?? [];

  const organizationJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": "https://casinoaftaler.dk/#organization",
    name: "Casinoaftaler.dk",
    url: "https://casinoaftaler.dk",
    dateModified: "2026-02-26",
    logo: {
      "@type": "ImageObject",
      url: "https://casinoaftaler.dk/icon-512x512.png",
      width: 512,
      height: 512,
    },
    description:
      "Casinoaftaler.dk er en dansk casino-guide med fokus på gennemsigtighed, testmetoder og ansvarligt spil.",
    foundingDate: "2021",
    founder: {
      "@type": "Person",
      "@id": "https://casinoaftaler.dk/forfatter/jonas#person",
    },
    employee: [
      {
        "@type": "Person",
        "@id": "https://casinoaftaler.dk/forfatter/jonas#person",
      },
      {
        "@type": "Person",
        "@id": "https://casinoaftaler.dk/forfatter/kevin#person",
      },
      {
        "@type": "Person",
        "@id": "https://casinoaftaler.dk/forfatter/ajse#person",
      },
    ],
    sameAs: [
      "https://www.youtube.com/@casinoaftaler",
      "https://www.instagram.com/casinoaftaler",
      "https://www.facebook.com/casinoaftaler",
    ],
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer support",
      url: "https://casinoaftaler.dk/kontakt",
      availableLanguage: "Danish",
    },
    publishingPrinciples: "https://casinoaftaler.dk/redaktionel-politik",
    knowsAbout: [
      "Online casino",
      "Casino bonus",
      "Spilleautomater",
      "Casino test",
      "Ansvarligt spil",
    ],
  };

  // WebSite schema removed – auto-injected on homepage by SEO.tsx

  // BreadcrumbList is auto-generated by SEO.tsx via buildBreadcrumbListSchema() – no manual injection needed.

  const missionPoints = [
    { icon: CheckCircle2, text: "At give ærlige og opdaterede anmeldelser" },
    { icon: Search, text: "At teste casinoer systematisk" },
    { icon: Heart, text: "At skabe et engageret community" },
    { icon: Sparkles, text: "At kombinere streaming og ekspertise" },
  ];

  const workMethods = [
    {
      icon: Gamepad2,
      title: "Vi tester casinoer praktisk",
      desc: "Hvert casino bliver testet af vores team med registrering, indbetaling og gameplay – ikke kun skrivebordsvurdering.",
    },
    {
      icon: RefreshCw,
      title: "Vi opdaterer bonusser løbende",
      desc: "Bonusser og vilkår ændres ofte. Vi holder vores anmeldelser opdateret, så du altid har de nyeste oplysninger.",
    },
    {
      icon: Search,
      title: "Vi analyserer vilkår",
      desc: "Omsætningskrav, tidsfrister og spilbidrag – vi nedbryder det hele, så du forstår hvad du accepterer.",
    },
    {
      icon: Eye,
      title: "Vi prioriterer gennemsigtighed",
      desc: "Vi fortæller tydeligt hvad der er godt og hvad der ikke er. Ingen skjulte agendaer.",
    },
    {
      icon: Scale,
      title: "Vi adskiller kommercielle samarbejder fra vurdering",
      desc: "Affiliate-partnerskaber påvirker aldrig vores redaktionelle vurderinger eller anbefalinger.",
    },
  ];

  const stats = [
    { icon: Clock, value: "7+", label: "Års samlet streaming-erfaring" },
    { icon: Trophy, value: "30+", label: "Testede danske casinoer" },
    { icon: Tv, value: "7000+", label: "Timers live streaming" },
    { icon: BookOpen, value: "160+", label: "Publicerede artikler & guides" },
    { icon: Users, value: "Aktivt", label: "Engageret community" },
  ];

  const trustPoints = [
    "Praktisk test af casinoer",
    "Løbende opdatering af bonusser",
    "Gennemsigtige vurderingskriterier",
    "Klar adskillelse mellem kommercielle samarbejder og redaktionel vurdering",
    "Fokus på ansvarligt spil",
  ];

  const disqualificationCriteria = [
    { text: "Manglende dansk licens fra Spillemyndigheden", link: "/casino-licenser", linkText: "dansk licens" },
    { text: "Uklare eller vildledende bonusvilkår", link: "/casino-bonus", linkText: "bonusvilkår" },
    { text: "Langsom udbetalingstid uden dokumenteret grund", link: "/casinoer/hurtig-udbetaling", linkText: "udbetalingstid" },
    { text: "Skjulte gebyrer ved ind- eller udbetaling", link: "/betalingsmetoder", linkText: "gebyrer" },
    { text: "Aggressiv eller uansvarlig markedsføring", link: "/ansvarligt-spil", linkText: "uansvarlig markedsføring" },
    { text: "Manglende tilslutning til ROFUS", link: null, linkText: null },
  ];

  return (
    <>
      <SEO
        title="Om teamet bag Casinoaftaler.dk | Streamere & Casinoeksperter"
        description="Mød teamet bag Casinoaftaler.dk. Læs om Jonas, Kevin og Ajse – casino-streamere og redaktører bag test, anmeldelser og udvikling."
        jsonLd={[organizationJsonLd]}
      />

      {/* ═══ HERO ═══ */}
      <section
        className="relative overflow-hidden py-16 text-white md:py-28"
        style={{
          backgroundImage: heroBackgroundImage
            ? `linear-gradient(135deg, hsl(260 70% 18% / 0.97), hsl(210 80% 22% / 0.95)), url(${heroBackgroundImage})`
            : "linear-gradient(135deg, hsl(260 70% 18%), hsl(250 60% 15%) 40%, hsl(210 80% 20%))",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <div className="container">
          <div className="mx-auto max-w-4xl text-center">
            <Badge variant="secondary" className="mb-6">
              <Users className="mr-1.5 h-3.5 w-3.5" />
              Om Teamet
            </Badge>
            <h1 className="mb-6 text-4xl font-bold tracking-tight md:text-6xl">
              Teamet bag Casinoaftaler.dk
            </h1>
            <p className="mb-4 text-xl font-semibold text-white/90 md:text-2xl">
              To streamere og én juridisk redaktør. Ét fælles mål.
              <br />
              At skabe gennemsigtighed i online casino i Danmark.
            </p>
            <p className="mx-auto max-w-2xl text-base text-white/70 md:text-lg">
              Fra Twitch-streams til systematisk test af casinoer – Casinoaftaler.dk er bygget på
              praktisk erfaring, community og gennemsigtighed.
            </p>

            {/* Profile images side-by-side */}
            <div className="mt-10 flex items-center justify-center gap-6 md:gap-10">
              <Link to="/forfatter/jonas" className="group">
                <div className="mx-auto h-28 w-28 overflow-hidden rounded-2xl border-4 border-white/20 transition-all duration-300 group-hover:border-white/50 group-hover:scale-105 md:h-36 md:w-36">
                  <img src={jonasImage} alt="Jonas – Grundlægger" className="h-full w-full object-cover object-top" loading="eager" />
                </div>
                <p className="mt-2 text-sm font-medium text-white/80">Jonas</p>
              </Link>
              <div className="flex flex-col items-center gap-1">
                <span className="text-3xl font-bold text-white/30">&</span>
              </div>
              <Link to="/forfatter/kevin" className="group">
                <div className="mx-auto h-28 w-28 overflow-hidden rounded-2xl border-4 border-white/20 transition-all duration-300 group-hover:border-white/50 group-hover:scale-105 md:h-36 md:w-36">
                  <img src={kevinImage} alt="Kevin – IT Medansvarlig" className="h-full w-full object-cover object-top" loading="eager" />
                </div>
                <p className="mt-2 text-sm font-medium text-white/80">Kevin</p>
              </Link>
              <div className="flex flex-col items-center gap-1">
                <span className="text-3xl font-bold text-white/30">&</span>
              </div>
              <Link to="/forfatter/ajse" className="group">
                <div className="mx-auto h-28 w-28 overflow-hidden rounded-2xl border-4 border-white/20 transition-all duration-300 group-hover:border-white/50 group-hover:scale-105 md:h-36 md:w-36">
                  <img src={ajseImage} alt="Ajse – Juridisk redaktør" className="h-full w-full object-cover object-top" loading="eager" />
                </div>
                <p className="mt-2 text-sm font-medium text-white/80">Ajse</p>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ═══ AUTHORITY POSITIONERING ═══ */}
      <div className="container pt-10 pb-0 md:pt-14">
        <p className="mx-auto max-w-3xl text-center text-muted-foreground leading-relaxed">
          Casinoaftaler.dk er en uafhængig dansk platform, der tester og analyserer online casinoer under dansk licens. Vi kombinerer praktisk erfaring, juridisk gennemgang og løbende overvågning af markedet.
        </p>
      </div>

      {/* ═══ FRA TWITCH TIL PLATFORM (Storytelling) ═══ */}
      <div className="container py-12 md:py-16">
        <AuthorMetaBar author="ajse" date="17-02-2026" readTime="18 Min." showFactCheck={true} showAffiliateDisclaimer={false} />
        <section className="mb-16">
          <h2 className="mb-6 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <Tv className="h-7 w-7 text-primary" />
            Fra Twitch til Casinoaftaler.dk
          </h2>
          <div className="grid gap-8 md:grid-cols-2">
            <div className="space-y-4">
              <p className="text-muted-foreground leading-relaxed">
                Det hele startede på Twitch. Jonas og Kevin streamede uafhængigt af hinanden, men
                fandt hurtigt fælles interesse for online casino, streaming og det community, der
                voksede op omkring dem.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                De begyndte at gæste hinandens streams, dele erfaringer og diskutere de casinoer,
                de testede. Seerne stillede spørgsmål – og det blev tydeligt, at der manglede et
                sted med ærlig og gennemsigtig information.
              </p>
            </div>
            <div className="space-y-4">
              <p className="text-muted-foreground leading-relaxed">
                Derfra voksede idéen om Casinoaftaler.dk – en platform bygget af streamere med
                praktisk erfaring, for spillere der ønsker gennemsigtighed.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                I dag kombinerer de streaming, systematisk test og community til en samlet
                platform, hvor anmeldelser bygger på reel erfaring – ikke kun skrivebordsvurdering.
              </p>
            </div>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ VORES MISSION ═══ */}
        <section className="mb-16">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <Target className="h-7 w-7 text-primary" />
            Vores mission
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-6">
            Vi arbejder hver dag for at gøre det nemmere og sikrere for danske spillere at navigere
            i verden af online casino. Vores tilgang bygger på reel erfaring, systematisk testning
            og et stærkt fokus på gennemsigtighed.
          </p>
          <div className="grid gap-3 sm:grid-cols-2">
            {missionPoints.map((point) => (
              <div
                key={point.text}
                className="flex items-center gap-3 rounded-lg border border-border bg-card p-4"
              >
                <point.icon className="h-5 w-5 flex-shrink-0 text-primary" />
                <span className="text-sm font-medium">{point.text}</span>
              </div>
            ))}
          </div>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link to="/saadan-tester-vi-casinoer">
              <Button variant="outline" size="sm">
                <ShieldCheck className="mr-1.5 h-4 w-4" />
                Vores testproces
              </Button>
            </Link>
            <Link to="/nye-casinoer">
              <Button variant="outline" size="sm">
                <Sparkles className="mr-1.5 h-4 w-4" />
                Nye Casinoer
              </Button>
            </Link>
            <Link to="/ansvarligt-spil">
              <Button variant="outline" size="sm">
                <Shield className="mr-1.5 h-4 w-4" />
                Spil med omtanke
              </Button>
            </Link>
          </div>
        </section>
      </div>

      {/* ═══ CITAT-SEKTION (visuelt adskilt) ═══ */}
      <section
        className="py-16 md:py-20"
        style={{
          background: "linear-gradient(135deg, hsl(260 50% 12%), hsl(230 40% 15%))",
        }}
      >
        <div className="container">
          <h2 className="mb-10 text-center text-3xl font-bold text-white flex items-center justify-center gap-2 md:text-4xl">
            <MessageSquare className="h-7 w-7" />
            Hvad driver os?
          </h2>
          <div className="grid gap-6 md:grid-cols-2">
            <Card className="border-white/10 bg-white/5 backdrop-blur-sm">
              <CardContent className="p-8">
                <Quote className="mb-4 h-8 w-8 text-primary/60" />
                <p className="mb-6 text-xl font-medium leading-relaxed text-white/90 italic">
                  "Streaming handler om energi. Casinoaftaler handler om gennemsigtighed."
                </p>
                <div className="flex items-center gap-3">
                   <div className="h-12 w-12 overflow-hidden rounded-xl border-2 border-primary/30">
                     <img src={jonasImage} alt="Jonas" className="h-full w-full object-cover object-top" />
                  </div>
                  <div>
                    <p className="font-semibold text-white">Jonas</p>
                    <p className="text-sm text-white/60">Grundlægger & Indholdsansvarlig</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-white/10 bg-white/5 backdrop-blur-sm">
              <CardContent className="p-8">
                <Quote className="mb-4 h-8 w-8 text-primary/60" />
                <p className="mb-6 text-xl font-medium leading-relaxed text-white/90 italic">
                  "Vi tester ikke bare casinoer – vi dokumenterer vores vurderinger."
                </p>
                <div className="flex items-center gap-3">
                   <div className="h-12 w-12 overflow-hidden rounded-xl border-2 border-primary/30">
                     <img src={kevinImage} alt="Kevin" className="h-full w-full object-cover object-top" />
                  </div>
                  <div>
                    <p className="font-semibold text-white">Kevin</p>
                    <p className="text-sm text-white/60">Casino-streamer & IT Medansvarlig</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Ajse quote – centered below */}
            <Card className="border-white/10 bg-white/5 backdrop-blur-sm md:col-span-2 md:max-w-xl md:mx-auto">
              <CardContent className="p-8">
                <Quote className="mb-4 h-8 w-8 text-primary/60" />
                <p className="mb-6 text-xl font-medium leading-relaxed text-white/90 italic">
                  "Gennemsigtighed starter med korrekt information – det er min opgave at sikre det."
                </p>
                <div className="flex items-center gap-3">
                  <div className="h-12 w-12 overflow-hidden rounded-xl border-2 border-primary/30">
                    <img src={ajseImage} alt="Ajse" className="h-full w-full object-cover object-top" />
                  </div>
                  <div>
                    <p className="font-semibold text-white">Ajse</p>
                    <p className="text-sm text-white/60">Juridisk redaktør & Compliance</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* ═══ TEAMET I TAL ═══ */}
      <div className="container py-12 md:py-16">
        <section className="mb-16">
          <h2 className="mb-8 text-center text-3xl font-bold flex items-center justify-center gap-2 md:text-4xl">
            <Zap className="h-7 w-7 text-primary" />
            Teamet i tal
          </h2>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-5">
            {stats.map((stat) => (
              <Card key={stat.label} className="border-border bg-card text-center">
                <CardContent className="p-6">
                  <stat.icon className="mx-auto mb-3 h-8 w-8 text-primary" />
                  <p className="text-3xl font-bold text-foreground md:text-4xl">{stat.value}</p>
                  <p className="mt-1 text-sm text-muted-foreground">{stat.label}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ VORES SKRIBENTER & REDAKTION (Author Hub) ═══ */}
        <section className="mb-16">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <Pen className="h-7 w-7 text-primary" />
            Vores skribenter & redaktion
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-6">
            Casinoaftaler.dk drives af tre faste skribenter med klare roller og ansvarsområder.
            Alle artikler, anmeldelser og guides produceres internt af redaktionen og faktatjekkes
            af en anden redaktør end forfatteren inden publicering.
          </p>
          <div className="grid gap-4 md:grid-cols-3">
            {/* Jonas */}
            <div className="rounded-xl border border-border bg-card p-5">
              <Link to="/forfatter/jonas" className="group">
                <div className="flex items-center gap-3 mb-3">
                  <img src={jonasImage} alt="Jonas – Grundlægger" className="h-12 w-12 rounded-full object-cover object-top ring-2 ring-border group-hover:ring-primary transition-colors" width={48} height={48} loading="lazy" />
                  <div>
                    <p className="font-semibold group-hover:text-primary transition-colors">Jonas</p>
                    <p className="text-xs text-muted-foreground">Grundlægger & Indholdsansvarlig</p>
                  </div>
                </div>
              </Link>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Ansvarlig for strategi, <Link to="/casino-anmeldelser" className="text-primary underline hover:text-primary/80">casino-anmeldelser</Link>, <Link to="/casino-bonus" className="text-primary underline hover:text-primary/80">bonusguides</Link> og <Link to="/community/slots" className="text-primary underline hover:text-primary/80">slots</Link>-indhold. Streamer med 4+ års erfaring.
              </p>
              <Link to="/forfatter/jonas" className="mt-3 inline-flex items-center text-sm font-medium text-primary hover:text-primary/80 transition-colors">
                Læs om Jonas – Grundlægger <ArrowRight className="ml-1 h-3.5 w-3.5" />
              </Link>
            </div>
            {/* Kevin */}
            <div className="rounded-xl border border-border bg-card p-5">
              <Link to="/forfatter/kevin" className="group">
                <div className="flex items-center gap-3 mb-3">
                  <img src={kevinImage} alt="Kevin – IT Medansvarlig" className="h-12 w-12 rounded-full object-cover object-top ring-2 ring-border group-hover:ring-primary transition-colors" width={48} height={48} loading="lazy" />
                  <div>
                    <p className="font-semibold group-hover:text-primary transition-colors">Kevin</p>
                    <p className="text-xs text-muted-foreground">Casino-streamer & IT Medansvarlig</p>
                  </div>
                </div>
              </Link>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Dækker <Link to="/betalingsmetoder" className="text-primary underline hover:text-primary/80">betalingsmetoder</Link>, <Link to="/casinoer/hurtig-udbetaling" className="text-primary underline hover:text-primary/80">udbetalingshastighed</Link>, spiludviklere og teknisk platformudvikling. Streamer med 3+ års erfaring.
              </p>
              <Link to="/forfatter/kevin" className="mt-3 inline-flex items-center text-sm font-medium text-primary hover:text-primary/80 transition-colors">
                Se Kevin – Casino & IT <ArrowRight className="ml-1 h-3.5 w-3.5" />
              </Link>
            </div>
            {/* Ajse */}
            <div className="rounded-xl border border-border bg-card p-5">
              <Link to="/forfatter/ajse" className="group">
                <div className="flex items-center gap-3 mb-3">
                  <img src={ajseImage} alt="Ajse – Juridisk redaktør" className="h-12 w-12 rounded-full object-cover object-top ring-2 ring-border group-hover:ring-primary transition-colors" width={48} height={48} loading="lazy" />
                  <div>
                    <p className="font-semibold group-hover:text-primary transition-colors">Ajse</p>
                    <p className="text-xs text-muted-foreground">Juridisk redaktør & Compliance</p>
                  </div>
                </div>
              </Link>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Ansvarlig for <Link to="/casino-licenser" className="text-primary underline hover:text-primary/80">licenser</Link>, <Link to="/ansvarligt-spil" className="text-primary underline hover:text-primary/80">ansvarligt spil</Link> og <Link to="/casino-nyheder" className="text-primary underline hover:text-primary/80">casino-nyheder</Link>. Jurastuderende med branchefokus.
              </p>
              <Link to="/forfatter/ajse" className="mt-3 inline-flex items-center text-sm font-medium text-primary hover:text-primary/80 transition-colors">
                Se Ajse – Juridisk redaktør <ArrowRight className="ml-1 h-3.5 w-3.5" />
              </Link>
            </div>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ SENESTE ARTIKLER FRA REDAKTIONEN ═══ */}
        {latestArticles.length > 0 && (
          <section className="mb-16">
            <h2 className="mb-2 text-3xl font-bold flex items-center gap-2 md:text-4xl">
              <Newspaper className="h-7 w-7 text-primary" />
              Seneste artikler fra redaktionen
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-6">
              Alle artikler skrives eller redigeres af vores faste redaktion og gennemgår dual fact-check før publicering.
            </p>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {latestArticles.map((article) => (
                <Link
                  key={article.id}
                  to={`/casino-nyheder/${article.slug}`}
                  className="group rounded-xl border border-border bg-card overflow-hidden transition-all hover:border-primary/30 hover:shadow-lg hover:shadow-primary/10 hover:-translate-y-1"
                >
                  {article.featured_image && (
                    <div className="aspect-video overflow-hidden">
                      <img
                        src={optimizeStorageImage(article.featured_image, 400, 70) ?? ""}
                        alt={article.title}
                        className="h-full w-full object-cover transition-transform group-hover:scale-105"
                        loading="lazy"
                        width={400}
                        height={225}
                      />
                    </div>
                  )}
                  <div className="p-4">
                    <p className="text-xs text-muted-foreground mb-1">
                      {article.published_at
                        ? new Date(article.published_at).toLocaleDateString("da-DK", { day: "numeric", month: "long", year: "numeric" })
                        : ""}
                      {" · "}
                      <span className="capitalize">{article.author_id === "ajse" ? "Ajse" : article.author_id === "kevin" ? "Kevin" : "Jonas"}</span>
                    </p>
                    <h3 className="font-semibold text-sm leading-snug group-hover:text-primary transition-colors line-clamp-2">
                      {article.title}
                    </h3>
                    {article.excerpt && (
                      <p className="mt-1.5 text-xs text-muted-foreground line-clamp-2">{article.excerpt}</p>
                    )}
                  </div>
                </Link>
              ))}
            </div>
            <div className="mt-6 text-center">
              <Link to="/casino-nyheder">
                <Button variant="outline" size="sm">
                  <Newspaper className="mr-1.5 h-4 w-4" />
                  Se alle nyheder
                  <ArrowRight className="ml-1.5 h-4 w-4" />
                </Button>
              </Link>
            </div>
          </section>
        )}

        <Separator className="my-10" />

        {/* ═══ KVALITETSSIKRING & FAKTATJEK ═══ */}
        <section className="mb-16">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <FileCheck className="h-7 w-7 text-primary" />
            Sådan sikrer vi kvalitet og faktatjek
          </h2>
          <div className="rounded-xl border border-border bg-gradient-to-br from-card to-accent/20 p-6 space-y-4">
            <p className="text-muted-foreground leading-relaxed">
              Alt indhold på Casinoaftaler.dk gennemgår et <strong>dual fact-check system</strong>:
              Ingen artikel publiceres uden at en anden redaktør end forfatteren har verificeret
              fakta, bonusvilkår og juridiske oplysninger.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Vi opretholder en <strong>klar adskillelse mellem kommercielt og redaktionelt indhold</strong>.
              Affiliate-partnerskaber påvirker aldrig vores vurderinger eller anbefalinger – dette
              er dokumenteret i vores <Link to="/forretningsmodel" className="text-primary underline hover:text-primary/80">forretningsmodel</Link> og <Link to="/redaktionel-politik" className="text-primary underline hover:text-primary/80">redaktionelle politik</Link>.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Alt reguleringsindhold – herunder licenser, lovgivning og ansvarligt spil –
              gennemgår <strong>juridisk review</strong> af Ajse, vores juridiske redaktør, inden publicering.
            </p>
          </div>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link to="/redaktionel-politik">
              <Button variant="outline" size="sm">
                <BookOpen className="mr-1.5 h-4 w-4" />
                Redaktionel politik
              </Button>
            </Link>
            <Link to="/forretningsmodel">
              <Button variant="outline" size="sm">
                <Scale className="mr-1.5 h-4 w-4" />
                Forretningsmodel
              </Button>
            </Link>
            <Link to="/saadan-tester-vi-casinoer">
              <Button variant="outline" size="sm">
                <ShieldCheck className="mr-1.5 h-4 w-4" />
                Se vores testmetode
              </Button>
            </Link>
            <Link to="/ansvarligt-spil">
              <Button variant="outline" size="sm">
                <Shield className="mr-1.5 h-4 w-4" />
                Om ansvarligt spil
              </Button>
            </Link>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ HVAD DISKVALIFICERER ET CASINO? ═══ */}
        <section className="mb-16">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <XCircle className="h-7 w-7 text-destructive" />
            Hvad diskvalificerer et casino?
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-6">
            Vi anbefaler kun casinoer, der lever op til vores strenge krav. Følgende kriterier
            medfører automatisk diskvalificering fra vores anbefalinger:
          </p>
          <div className="rounded-xl border border-border bg-card p-6">
            <ul className="space-y-3">
              {disqualificationCriteria.map((item) => (
                <li key={item.text} className="flex items-start gap-3">
                  <XCircle className="mt-0.5 h-5 w-5 flex-shrink-0 text-destructive" />
                  <span className="text-sm font-medium">
                    {item.link ? (
                      <>
                        {item.text.split(item.linkText!)[0]}
                        <Link to={item.link} className="text-primary underline hover:text-primary/80">{item.linkText}</Link>
                        {item.text.split(item.linkText!)[1]}
                      </>
                    ) : (
                      item.text
                    )}
                  </span>
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-6">
            <Link to="/saadan-tester-vi-casinoer">
              <Button variant="outline" size="sm">
                <ShieldCheck className="mr-1.5 h-4 w-4" />
                Læs mere om vores testkriterier
                <ArrowRight className="ml-1.5 h-4 w-4" />
              </Button>
            </Link>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ VORES TESTMETODE ═══ */}
        <section className="mb-12">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <ShieldCheck className="h-7 w-7 text-primary" />
            Vores testmetode
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Alle anmeldelser på Casinoaftaler.dk bygger på praktisk test udført af vores team. Vi opretter konti,
            indbetaler, spiller og evaluerer hvert casino ud fra faste kriterier – herunder spilsortiment, bonusvilkår,
            kundeservice og udbetalingshastighed.
          </p>
          <Link to="/saadan-tester-vi-casinoer">
            <Button variant="outline" size="sm">
              <ShieldCheck className="mr-1.5 h-4 w-4" />
              Læs om vores testproces
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>

        <Separator className="my-10" />

        {/* ═══ SÅDAN ARBEJDER TEAMET ═══ */}
        <section className="mb-16">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <BookOpen className="h-7 w-7 text-primary" />
            Sådan arbejder teamet
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-8">
            Vores arbejdsproces er designet til at sikre, at alle anmeldelser og anbefalinger
            bygger på reel test og dokumenteret vurdering.
          </p>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {workMethods.map((method) => (
              <Card key={method.title} className="border-border bg-card">
                <CardContent className="p-6">
                  <method.icon className="mb-3 h-6 w-6 text-primary" />
                  <h3 className="mb-2 font-semibold">{method.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">{method.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
          <div className="mt-8">
            <Link to="/saadan-tester-vi-casinoer">
              <Button variant="outline" size="sm">
                <ShieldCheck className="mr-1.5 h-4 w-4" />
                Sådan tester vi casinoer
              </Button>
            </Link>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ HVORFOR STOLE PÅ OS ═══ */}
        <section className="mb-16">
          <h2 className="mb-6 text-3xl font-bold flex items-center gap-2 md:text-4xl">
            <ShieldCheck className="h-7 w-7 text-primary" />
            Hvorfor stole på Casinoaftaler.dk?
          </h2>
          <div className="rounded-xl border border-border bg-card p-6 md:p-8">
            <div className="space-y-4">
              {trustPoints.map((point) => (
                <div key={point} className="flex items-start gap-3">
                  <CheckCircle2 className="mt-0.5 h-5 w-5 flex-shrink-0 text-primary" />
                  <span className="font-medium">{point}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        <Separator className="my-10" />

        {/* ═══ FORRETNINGSMODEL ═══ */}
        <section className="mb-12">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <Scale className="h-7 w-7 text-primary" />
            Forretningsmodel
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Casinoaftaler.dk finansieres gennem affiliate-samarbejder med udvalgte casinoer. Det betyder, at vi
            modtager kommission, når brugere tilmelder sig via vores links. Vores vurderinger og anbefalinger
            er dog altid uafhængige og bygger på faste testkriterier.
          </p>
          <Link to="/forretningsmodel">
            <Button variant="outline" size="sm">
              <Scale className="mr-1.5 h-4 w-4" />
              Læs vores forretningsmodel
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>

        <Separator className="my-10" />

        {/* ═══ REDAKTIONEL POLITIK ═══ */}
        <section className="mb-12">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <BookOpen className="h-7 w-7 text-primary" />
            Redaktionel politik
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Vores redaktionelle politik sikrer en klar adskillelse mellem kommercielt og redaktionelt indhold.
            Alt indhold produceres af vores team, opdateres løbende og følger dokumenterede retningslinjer
            for kvalitet og objektivitet.
          </p>

          <div className="grid gap-4 md:grid-cols-3 mb-6">
            <Card className="border-border bg-card">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 mb-2">
                  <Users className="h-5 w-5 text-primary" />
                  <h3 className="font-semibold text-sm">Rollefordeling</h3>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Jonas står for anmeldelser og guides. Kevin dækker teknik og platformudvikling. Ajse er juridisk redaktør og dækker compliance, licenser og ansvarligt spil. Alle artikler faktatjekkes af en anden redaktør end forfatteren.
                </p>
              </CardContent>
            </Card>
            <Card className="border-border bg-card">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 mb-2">
                  <CheckCircle2 className="h-5 w-5 text-primary" />
                  <h3 className="font-semibold text-sm">Faktatjek</h3>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Alle artikler gennemgås af en anden redaktør end forfatteren. Bonusvilkår verificeres manuelt mod casinoernes egne sider før publicering.
                </p>
              </CardContent>
            </Card>
            <Card className="border-border bg-card">
              <CardContent className="p-5">
                <div className="flex items-center gap-2 mb-2">
                  <RefreshCw className="h-5 w-5 text-primary" />
                  <h3 className="font-semibold text-sm">Opdateringsfrekvens</h3>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Anmeldelser gennemgås kvartalsvis. Bonusguides opdateres når vilkår ændres. Forældet indhold fjernes eller markeres tydeligt.
                </p>
              </CardContent>
            </Card>
          </div>

          <Link to="/redaktionel-politik">
            <Button variant="outline" size="sm">
              <BookOpen className="mr-1.5 h-4 w-4" />
              Læs den fulde redaktionelle politik
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>

        <Separator className="my-10" />

        {/* ═══ ANSVARLIGT SPIL ═══ */}
        <section className="mb-12">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <Shield className="h-7 w-7 text-primary" />
            Ansvarligt spil
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Vi anbefaler kun licenserede operatører og arbejder aktivt for ansvarligt spil. Alle casinoer på vores platform er tilsluttet ROFUS, og vi opfordrer spillere til at bruge de tilgængelige værktøjer til at sætte grænser for indbetaling, tab og spilletid.
          </p>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Har du brug for hjælp, kan du kontakte <a href="https://www.stopspillet.dk" target="_blank" rel="noopener noreferrer" className="text-primary underline hover:text-primary/80">StopSpillet</a> på telefon 70 22 28 25 (gratis og anonymt) eller udelukke dig selv via <a href="https://www.rofus.nu" target="_blank" rel="noopener noreferrer" className="text-primary underline hover:text-primary/80">ROFUS.nu</a>.
          </p>
          <Link to="/ansvarligt-spil">
            <Button variant="outline" size="sm">
              <Shield className="mr-1.5 h-4 w-4" />
              Læs mere om ansvarligt spil
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>

        <Separator className="my-10" />

        {/* ═══ KONTAKT & IMPRESSUM ═══ */}
        <section className="mb-16">
          <h2 className="mb-4 text-3xl font-bold flex items-center gap-2">
            <MessageSquare className="h-7 w-7 text-primary" />
            Kontakt
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            Har du spørgsmål, feedback eller ønsker du at samarbejde med os? Vi hører gerne fra dig.
          </p>
          <Link to="/kontakt">
            <Button variant="outline" size="sm">
              <MessageSquare className="mr-1.5 h-4 w-4" />
              Kontakt os
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
          </Link>
        </section>
      </div>

      {/* ═══ CTA SEKTION (visuelt adskilt) ═══ */}
      <section
        className="py-16 md:py-20"
        style={{
          background: "linear-gradient(135deg, hsl(260 60% 15%), hsl(220 50% 18%))",
        }}
      >
        <div className="container text-center">
          <h2 className="mb-4 text-3xl font-bold text-white md:text-4xl">
            Vil du vide mere om vores testmetode?
          </h2>
          <p className="mx-auto mb-8 max-w-xl text-white/70">
            Se hvordan vi arbejder, eller lær vores team bedre at kende via deres personlige profiler.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link to="/saadan-tester-vi-casinoer">
              <Button size="lg" className="font-semibold">
                <ShieldCheck className="mr-2 h-5 w-5" />
                Sådan tester vi casinoer
              </Button>
            </Link>
            <Link to="/forfatter/jonas">
              <Button variant="outline" size="lg" className="border-white/30 text-white bg-white/10 hover:bg-white/20 font-semibold">
                Læs om Jonas – Grundlægger
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
            <Link to="/forfatter/kevin">
              <Button variant="outline" size="lg" className="border-white/30 text-white bg-white/10 hover:bg-white/20 font-semibold">
                Se Kevin – Casino & IT
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
            <Link to="/forfatter/ajse">
              <Button variant="outline" size="lg" className="border-white/30 text-white bg-white/10 hover:bg-white/20 font-semibold">
                Se Ajse – Juridisk redaktør
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* ═══ RELATEREDE GUIDES ═══ */}
      <div className="container py-12 md:py-16">
        <AuthorBio author="ajse" showCommunity={false} />
        <RelatedGuides currentPath="/om" maxLinks={6} />
      </div>
    </>
  );
};

export default OmTeamet;
