/**
 * Sidebar navigation data for content/money pages.
 * Follows the top menu structure: Casinoer, Nye Casinoer, Casinospil, Live Casino,
 * Casino Bonus, Betalingsmetoder, Spiludviklere, Casino Anmeldelser.
 */

export interface SidebarLink {
  to: string;
  label: string;
}

export interface SidebarCategory {
  title: string;
  iconName: string;
  hubTo?: string; // link for collapsed "Se alle" / category header
  links: SidebarLink[];
}

export const SIDEBAR_CATEGORIES: SidebarCategory[] = [
  {
    title: "Casinoer",
    iconName: "crown",
    hubTo: "/top-10-casino-online",
    links: [
      { to: "/top-10-casino-online", label: "Top 10 Online Casino" },
      { to: "/casinoer/hurtig-udbetaling", label: "Hurtig Udbetaling" },
      { to: "/casinoer/hoej-rtp", label: "Høj RTP" },
      { to: "/casino-licenser", label: "Licenserede Casinoer" },
      { to: "/casino-uden-konto", label: "Casino uden Konto" },
      { to: "/casinoer/mobil-casinoer", label: "Mobil Casinoer" },
      { to: "/mobil-casino", label: "Mobil Casino Guide" },
      { to: "/casinoer/crypto-casino", label: "Crypto Casino" },
      { to: "/casinoer/vr-casinoer", label: "VR Casinoer" },
      { to: "/casinoer/spil-casino-for-sjov", label: "Spil Casino for Sjov" },
      { to: "/casinoer/casino-og-skat", label: "Casino og Skat" },
    ],
  },
  {
    title: "Nye Casinoer",
    iconName: "sparkles",
    hubTo: "/nye-casinoer",
    links: [
      { to: "/nye-casinoer", label: "Nye Casinoer 2026" },
      { to: "/nye-casinoer/dansk-licens", label: "Med Dansk Licens" },
      { to: "/nye-casinoer/uden-rofus", label: "Uden ROFUS" },
      { to: "/nye-casinoer/hurtig-udbetaling", label: "Hurtig Udbetaling" },
      { to: "/nye-casinoer/bonus-uden-indbetaling", label: "Bonus uden Indbetaling" },
      { to: "/nye-casinoer/trustly", label: "Med Trustly" },
      { to: "/nye-casinoer/mitid", label: "Med MitID" },
      { to: "/nye-casinoer/lav-wagering", label: "Lav Wagering" },
      { to: "/nye-casinoer/vs-etablerede", label: "Nye vs Etablerede" },
    ],
  },
  {
    title: "Casinospil",
    iconName: "dices",
    hubTo: "/casinospil",
    links: [
      { to: "/casinospil", label: "Alle Casinospil" },
      { to: "/casinospil/spillemaskiner", label: "Spillemaskiner" },
      { to: "/casinospil/blackjack", label: "Blackjack" },
      { to: "/casinospil/roulette", label: "Roulette" },
      { to: "/casinospil/poker", label: "Poker" },
      { to: "/casinospil/baccarat", label: "Baccarat" },
      { to: "/casinospil/craps", label: "Craps" },
      { to: "/casinospil/online-lotteri", label: "Online Lotteri" },
      { to: "/megaways-slots", label: "Megaways Slots" },
      { to: "/jackpot-slots", label: "Jackpot Slots" },
      { to: "/bonus-buy-slots", label: "Bonus Buy Slots" },
    ],
  },
  {
    title: "Live Casino",
    iconName: "tv",
    hubTo: "/live-casino",
    links: [
      { to: "/live-casino", label: "Live Casino" },
      { to: "/live-casino/blackjack", label: "Live Blackjack" },
      { to: "/live-casino/roulette", label: "Live Roulette" },
      { to: "/live-casino/baccarat", label: "Live Baccarat" },
      { to: "/live-casino/lightning-roulette", label: "Lightning Roulette" },
      { to: "/live-casino/monopoly-live", label: "Monopoly Live" },
      { to: "/live-casino/game-shows", label: "Game Shows" },
      { to: "/live-casino/crazy-time", label: "Crazy Time" },
      { to: "/live-casino/dream-catcher", label: "Dream Catcher" },
      { to: "/live-casino/deal-or-no-deal", label: "Deal or No Deal" },
      { to: "/live-casino/strategi", label: "Live Casino Strategi" },
      { to: "/live-casino/udbydere", label: "Live Casino Udbydere" },
    ],
  },
  {
    title: "Casino Bonus",
    iconName: "gift",
    hubTo: "/casino-bonus",
    links: [
      { to: "/casino-bonus", label: "Casino Bonus" },
      { to: "/velkomstbonus", label: "Velkomstbonus" },
      { to: "/free-spins", label: "Free Spins" },
      { to: "/bonus-uden-indbetaling", label: "Bonus uden Indbetaling" },
      { to: "/no-sticky-bonus", label: "No-Sticky Bonus" },
      { to: "/sticky-bonus", label: "Sticky Bonus" },
      { to: "/cashback-bonus", label: "Cashback Bonus" },
      { to: "/reload-bonus", label: "Reload Bonus" },
      { to: "/free-spins-i-dag", label: "Free Spins i Dag" },
      { to: "/omsaetningskrav", label: "Omsætningskrav" },
      { to: "/indskudsbonus", label: "Indskudsbonus" },
      { to: "/bonus-uden-omsaetningskrav", label: "Bonus uden Omsætningskrav" },
    ],
  },
  {
    title: "Betalingsmetoder",
    iconName: "creditCard",
    links: [
      { to: "/betalingsmetoder", label: "Alle Betalingsmetoder" },
      { to: "/betalingsmetoder/apple-pay", label: "Apple Pay" },
      { to: "/betalingsmetoder/mobilepay", label: "MobilePay" },
      { to: "/betalingsmetoder/paypal", label: "PayPal" },
      { to: "/betalingsmetoder/skrill", label: "Skrill" },
      { to: "/betalingsmetoder/trustly", label: "Trustly" },
      { to: "/betalingsmetoder/zimpler", label: "Zimpler" },
      { to: "/betalingsmetoder/paysafecard", label: "Paysafecard" },
      { to: "/betalingsmetoder/bankoverforsler", label: "Bankoverførsel" },
      { to: "/betalingsmetoder/visa-mastercard", label: "Visa / Mastercard" },
      { to: "/betalingsmetoder/revolut", label: "Revolut" },
    ],
  },
  {
    title: "Spiludviklere",
    iconName: "gamepad2",
    links: [
      { to: "/spiludviklere", label: "Alle Spiludviklere" },
      { to: "/spiludviklere/netent", label: "NetEnt" },
      { to: "/spiludviklere/pragmatic-play", label: "Pragmatic Play" },
      { to: "/spiludviklere/evolution-gaming", label: "Evolution Gaming" },
      { to: "/spiludviklere/relax-gaming", label: "Relax Gaming" },
      { to: "/spiludviklere/play-n-go", label: "Play'n GO" },
      { to: "/spiludviklere/hacksaw-gaming", label: "Hacksaw Gaming" },
      { to: "/spiludviklere/nolimit-city", label: "Nolimit City" },
      { to: "/spiludviklere/elk-studios", label: "ELK Studios" },
      { to: "/spiludviklere/yggdrasil", label: "Yggdrasil" },
      { to: "/spiludviklere/microgaming", label: "Microgaming" },
      { to: "/spiludviklere/red-tiger", label: "Red Tiger" },
      { to: "/spiludviklere/big-time-gaming", label: "Big Time Gaming" },
      { to: "/spiludviklere/thunderkick", label: "Thunderkick" },
      { to: "/spiludviklere/blueprint-gaming", label: "Blueprint Gaming" },
      { to: "/spiludviklere/push-gaming", label: "Push Gaming" },
      { to: "/spiludviklere/quickspin", label: "Quickspin" },
      { to: "/spiludviklere/isoftbet", label: "iSoftBet" },
      { to: "/spiludviklere/betsoft", label: "Betsoft" },
      { to: "/spiludviklere/wazdan", label: "Wazdan" },
      { to: "/spiludviklere/endorphina", label: "Endorphina" },
      { to: "/spiludviklere/stakelogic", label: "Stakelogic" },
      { to: "/spiludviklere/booming-games", label: "Booming Games" },
    ],
  },
  {
    title: "Casino Anmeldelser",
    iconName: "star",
    links: [
      { to: "/casino-anmeldelser", label: "Alle Anmeldelser" },
      { to: "/casino-anmeldelser/spildansknu", label: "SpilDanskNu" },
      { to: "/casino-anmeldelser/spilleautomaten", label: "Spilleautomaten" },
      { to: "/casino-anmeldelser/betinia", label: "Betinia" },
      { to: "/casino-anmeldelser/campobet", label: "Campobet" },
      { to: "/casino-anmeldelser/swift-casino", label: "Swift Casino" },
      { to: "/casino-anmeldelser/luna-casino", label: "Luna Casino" },
      { to: "/casino-anmeldelser/playkasino", label: "PlayKasino" },
      { to: "/casino-anmeldelser/leovegas", label: "LeoVegas" },
      { to: "/casino-anmeldelser/mr-green", label: "Mr Green" },
      { to: "/casino-anmeldelser/unibet", label: "Unibet" },
      { to: "/casino-anmeldelser/bet365", label: "bet365" },
      { to: "/casino-anmeldelser/comeon", label: "ComeOn" },
      { to: "/casino-anmeldelser/danske-spil", label: "Danske Spil" },
      { to: "/casino-anmeldelser/getlucky", label: "GetLucky" },
      { to: "/casino-anmeldelser/888-casino", label: "888 Casino" },
      { to: "/casino-anmeldelser/betano", label: "Betano" },
      { to: "/casino-anmeldelser/royal-casino", label: "Royal Casino" },
      { to: "/casino-anmeldelser/mr-vegas", label: "Mr Vegas" },
      { to: "/casino-anmeldelser/videoslots", label: "Videoslots" },
      { to: "/casino-anmeldelser/nordicbet", label: "NordicBet" },
      { to: "/casino-anmeldelser/spilnu", label: "Spilnu" },
      { to: "/casino-anmeldelser/stake-casino", label: "Stake Casino" },
    ],
  },
];
