/**
 * Sidebar navigation data for content/money pages.
 * Follows the top menu structure: Casinoer, Nye Casinoer, Casinospil, Live Casino,
 * Casino Bonus, Betalingsmetoder, Spiludviklere, Casino Anmeldelser.
 */

export interface SidebarLink {
  to: string;
  label: string;
  iconName?: string;
  logoUrl?: string;
}

export interface SidebarCategory {
  title: string;
  iconName: string;
  hubTo?: string; // link for collapsed "Se alle" / category header
  links: SidebarLink[];
}

export const SIDEBAR_CATEGORIES: SidebarCategory[] = [
  {
    title: "Casinoer",
    iconName: "crown",
    hubTo: "/top-10-casino-online",
    links: [
      { to: "/top-10-casino-online", label: "Top 10 Online Casino", iconName: "trophy" },
      { to: "/casinoer/hurtig-udbetaling", label: "Hurtig Udbetaling", iconName: "zap" },
      { to: "/casinoer/hoej-rtp", label: "Høj RTP", iconName: "trending-up" },
      { to: "/casino-licenser", label: "Licenserede Casinoer", iconName: "shield-check" },
      { to: "/casino-uden-konto", label: "Casino uden Konto", iconName: "user-x" },
      { to: "/casinoer/mobil-casinoer", label: "Mobil Casinoer", iconName: "smartphone" },
      { to: "/mobil-casino", label: "Mobil Casino Guide", iconName: "tablet-smartphone" },
      { to: "/casinoer/crypto-casino", label: "Crypto Casino", iconName: "bitcoin" },
      { to: "/casinoer/vr-casinoer", label: "VR Casinoer", iconName: "glasses" },
      { to: "/casinoer/spil-casino-for-sjov", label: "Spil Casino for Sjov", iconName: "gamepad-2" },
      { to: "/casinoer/casino-og-skat", label: "Casino og Skat", iconName: "receipt" },
    ],
  },
  {
    title: "Nye Casinoer",
    iconName: "sparkles",
    hubTo: "/nye-casinoer",
    links: [
      { to: "/nye-casinoer", label: "Nye Casinoer 2026", iconName: "calendar" },
      { to: "/nye-casinoer/dansk-licens", label: "Med Dansk Licens", iconName: "shield" },
      { to: "/nye-casinoer/uden-rofus", label: "Uden ROFUS", iconName: "shield-off" },
      { to: "/nye-casinoer/hurtig-udbetaling", label: "Hurtig Udbetaling", iconName: "zap" },
      { to: "/nye-casinoer/bonus-uden-indbetaling", label: "Bonus uden Indbetaling", iconName: "gift" },
      { to: "/nye-casinoer/trustly", label: "Med Trustly", iconName: "banknote" },
      { to: "/nye-casinoer/mitid", label: "Med MitID", iconName: "scan-line" },
      { to: "/nye-casinoer/lav-wagering", label: "Lav Wagering", iconName: "percent" },
      { to: "/nye-casinoer/vs-etablerede", label: "Nye vs Etablerede", iconName: "scale" },
    ],
  },
  {
    title: "Casinospil",
    iconName: "dices",
    hubTo: "/casinospil",
    links: [
      { to: "/casinospil", label: "Alle Casinospil", iconName: "layout-grid" },
      { to: "/casinospil/spillemaskiner", label: "Spillemaskiner", iconName: "cherry" },
      { to: "/casinospil/blackjack", label: "Blackjack", iconName: "spade" },
      { to: "/casinospil/roulette", label: "Roulette", iconName: "circle-dot" },
      { to: "/casinospil/poker", label: "Poker", iconName: "club" },
      { to: "/casinospil/baccarat", label: "Baccarat", iconName: "spade" },
      { to: "/casinospil/craps", label: "Craps", iconName: "dice-5" },
      { to: "/casinospil/online-lotteri", label: "Online Lotteri", iconName: "ticket" },
      { to: "/megaways-slots", label: "Megaways Slots", iconName: "layers" },
      { to: "/jackpot-slots", label: "Jackpot Slots", iconName: "trophy" },
      { to: "/bonus-buy-slots", label: "Bonus Buy Slots", iconName: "shopping-cart" },
    ],
  },
  {
    title: "Live Casino",
    iconName: "tv",
    hubTo: "/live-casino",
    links: [
      { to: "/live-casino", label: "Live Casino", iconName: "tv" },
      { to: "/live-casino/blackjack", label: "Live Blackjack", iconName: "spade" },
      { to: "/live-casino/roulette", label: "Live Roulette", iconName: "circle-dot" },
      { to: "/live-casino/baccarat", label: "Live Baccarat", iconName: "club" },
      { to: "/live-casino/lightning-roulette", label: "Lightning Roulette", iconName: "zap" },
      { to: "/live-casino/monopoly-live", label: "Monopoly Live", iconName: "building-2" },
      { to: "/live-casino/game-shows", label: "Game Shows", iconName: "tv" },
      { to: "/live-casino/crazy-time", label: "Crazy Time", iconName: "clock" },
      { to: "/live-casino/dream-catcher", label: "Dream Catcher", iconName: "target" },
      { to: "/live-casino/deal-or-no-deal", label: "Deal or No Deal", iconName: "briefcase" },
      { to: "/live-casino/strategi", label: "Live Casino Strategi", iconName: "brain" },
      { to: "/live-casino/udbydere", label: "Live Casino Udbydere", iconName: "users" },
    ],
  },
  {
    title: "Casino Bonus",
    iconName: "gift",
    hubTo: "/casino-bonus",
    links: [
      { to: "/casino-bonus", label: "Casino Bonus", iconName: "gift" },
      { to: "/velkomstbonus", label: "Velkomstbonus", iconName: "party-popper" },
      { to: "/free-spins", label: "Free Spins", iconName: "rotate-cw" },
      { to: "/bonus-uden-indbetaling", label: "Bonus uden Indbetaling", iconName: "gift" },
      { to: "/no-sticky-bonus", label: "No-Sticky Bonus", iconName: "unlink" },
      { to: "/sticky-bonus", label: "Sticky Bonus", iconName: "link" },
      { to: "/cashback-bonus", label: "Cashback Bonus", iconName: "undo-2" },
      { to: "/reload-bonus", label: "Reload Bonus", iconName: "refresh-cw" },
      { to: "/free-spins-i-dag", label: "Free Spins i Dag", iconName: "calendar-check" },
      { to: "/omsaetningskrav", label: "Omsætningskrav", iconName: "calculator" },
      { to: "/indskudsbonus", label: "Indskudsbonus", iconName: "piggy-bank" },
      { to: "/bonus-uden-omsaetningskrav", label: "Bonus uden Omsætningskrav", iconName: "circle-check" },
    ],
  },
  {
    title: "Betalingsmetoder",
    iconName: "creditCard",
    hubTo: "/betalingsmetoder",
    links: [
      { to: "/betalingsmetoder", label: "Alle Betalingsmetoder", iconName: "credit-card" },
      { to: "/betalingsmetoder/apple-pay", label: "Apple Pay", iconName: "apple" },
      { to: "/betalingsmetoder/mobilepay", label: "MobilePay", iconName: "smartphone" },
      { to: "/betalingsmetoder/paypal", label: "PayPal", iconName: "wallet" },
      { to: "/betalingsmetoder/skrill", label: "Skrill", iconName: "credit-card" },
      { to: "/betalingsmetoder/trustly", label: "Trustly", iconName: "banknote" },
      { to: "/betalingsmetoder/zimpler", label: "Zimpler", iconName: "send" },
      { to: "/betalingsmetoder/paysafecard", label: "Paysafecard", iconName: "shield" },
      { to: "/betalingsmetoder/bankoverforsler", label: "Bankoverførsel", iconName: "landmark" },
      { to: "/betalingsmetoder/visa-mastercard", label: "Visa / Mastercard", iconName: "credit-card" },
      { to: "/betalingsmetoder/revolut", label: "Revolut", iconName: "circle-dollar-sign" },
    ],
  },
  {
    title: "Spiludviklere",
    iconName: "gamepad2",
    hubTo: "/spiludviklere",
    links: [
      { to: "/spiludviklere", label: "Alle Spiludviklere", iconName: "layout-grid" },
      { to: "/spiludviklere/netent", label: "NetEnt", logoUrl: "/src/assets/providers/netent.webp" },
      { to: "/spiludviklere/pragmatic-play", label: "Pragmatic Play", logoUrl: "/src/assets/providers/pragmatic-play.webp" },
      { to: "/spiludviklere/evolution-gaming", label: "Evolution Gaming", logoUrl: "/src/assets/providers/evolution-gaming.webp" },
      { to: "/spiludviklere/relax-gaming", label: "Relax Gaming", logoUrl: "/src/assets/providers/relax-gaming.webp" },
      { to: "/spiludviklere/play-n-go", label: "Play'n GO", logoUrl: "/src/assets/providers/play-n-go.webp" },
      { to: "/spiludviklere/hacksaw-gaming", label: "Hacksaw Gaming", logoUrl: "/src/assets/providers/hacksaw-gaming.webp" },
      { to: "/spiludviklere/nolimit-city", label: "Nolimit City", logoUrl: "/src/assets/providers/nolimit-city.webp" },
      { to: "/spiludviklere/elk-studios", label: "ELK Studios", logoUrl: "/src/assets/providers/elk-studios.webp" },
      { to: "/spiludviklere/yggdrasil", label: "Yggdrasil", logoUrl: "/src/assets/providers/yggdrasil.webp" },
      { to: "/spiludviklere/microgaming", label: "Microgaming", logoUrl: "/src/assets/providers/microgaming.webp" },
      { to: "/spiludviklere/red-tiger", label: "Red Tiger", logoUrl: "/src/assets/providers/red-tiger.webp" },
      { to: "/spiludviklere/big-time-gaming", label: "Big Time Gaming", logoUrl: "/src/assets/providers/big-time-gaming.webp" },
      { to: "/spiludviklere/thunderkick", label: "Thunderkick", logoUrl: "/src/assets/providers/thunderkick.webp" },
      { to: "/spiludviklere/blueprint-gaming", label: "Blueprint Gaming", logoUrl: "/src/assets/providers/blueprint-gaming.webp" },
      { to: "/spiludviklere/push-gaming", label: "Push Gaming", logoUrl: "/src/assets/providers/push-gaming.webp" },
      { to: "/spiludviklere/quickspin", label: "Quickspin", logoUrl: "/src/assets/providers/quickspin.webp" },
      { to: "/spiludviklere/isoftbet", label: "iSoftBet", logoUrl: "/src/assets/providers/isoftbet.webp" },
      { to: "/spiludviklere/betsoft", label: "Betsoft", logoUrl: "/src/assets/providers/betsoft.webp" },
      { to: "/spiludviklere/wazdan", label: "Wazdan", logoUrl: "/src/assets/providers/wazdan.webp" },
      { to: "/spiludviklere/endorphina", label: "Endorphina", logoUrl: "/src/assets/providers/endorphina.webp" },
      { to: "/spiludviklere/stakelogic", label: "Stakelogic", logoUrl: "/src/assets/providers/stakelogic.webp" },
      { to: "/spiludviklere/booming-games", label: "Booming Games", logoUrl: "/src/assets/providers/booming-games.webp" },
    ],
  },
  {
    title: "Casino Anmeldelser",
    iconName: "star",
    hubTo: "/casino-anmeldelser",
    links: [
      { to: "/casino-anmeldelser", label: "Alle Anmeldelser", iconName: "layout-grid" },
      { to: "/casino-anmeldelser/spildansknu", label: "SpilDanskNu", logoUrl: "/src/assets/casino-logos/spildansknu.webp" },
      { to: "/casino-anmeldelser/spilleautomaten", label: "Spilleautomaten", logoUrl: "/src/assets/casino-logos/spilleautomaten.webp" },
      { to: "/casino-anmeldelser/betinia", label: "Betinia", logoUrl: "/src/assets/casino-logos/betinia.webp" },
      { to: "/casino-anmeldelser/campobet", label: "Campobet", logoUrl: "/src/assets/casino-logos/campobet.webp" },
      { to: "/casino-anmeldelser/swift-casino", label: "Swift Casino", logoUrl: "/src/assets/casino-logos/swift-casino.webp" },
      { to: "/casino-anmeldelser/luna-casino", label: "Luna Casino", logoUrl: "/src/assets/casino-logos/luna-casino.webp" },
      { to: "/casino-anmeldelser/playkasino", label: "PlayKasino", logoUrl: "/src/assets/casino-logos/playkasino.webp" },
      { to: "/casino-anmeldelser/leovegas", label: "LeoVegas", logoUrl: "/src/assets/casino-logos/leovegas.webp" },
      { to: "/casino-anmeldelser/mr-green", label: "Mr Green", logoUrl: "/src/assets/reviews/mrgreen.webp" },
      { to: "/casino-anmeldelser/unibet", label: "Unibet", logoUrl: "/src/assets/reviews/unibet.webp" },
      { to: "/casino-anmeldelser/bet365", label: "bet365", logoUrl: "/src/assets/casino-logos/bet365.jpg" },
      { to: "/casino-anmeldelser/comeon", label: "ComeOn", logoUrl: "/src/assets/casino-logos/comeon.webp" },
      { to: "/casino-anmeldelser/danske-spil", label: "Danske Spil", logoUrl: "/src/assets/casino-logos/danskespil.webp" },
      { to: "/casino-anmeldelser/getlucky", label: "GetLucky", logoUrl: "/src/assets/reviews/getlucky.webp" },
      { to: "/casino-anmeldelser/888-casino", label: "888 Casino", logoUrl: "/src/assets/casino-logos/888casino.webp" },
      { to: "/casino-anmeldelser/betano", label: "Betano", logoUrl: "/src/assets/reviews/betano.webp" },
      { to: "/casino-anmeldelser/royal-casino", label: "Royal Casino", logoUrl: "/src/assets/casino-logos/royal-casino.webp" },
      { to: "/casino-anmeldelser/mr-vegas", label: "Mr Vegas", logoUrl: "/src/assets/casino-logos/mrvegas.webp" },
      { to: "/casino-anmeldelser/videoslots", label: "Videoslots", logoUrl: "/src/assets/casino-logos/videoslots.webp" },
      { to: "/casino-anmeldelser/nordicbet", label: "NordicBet", logoUrl: "/src/assets/reviews/nordicbet.webp" },
      { to: "/casino-anmeldelser/spilnu", label: "Spilnu", logoUrl: "/src/assets/reviews/spilnu.webp" },
      { to: "/casino-anmeldelser/stake-casino", label: "Stake Casino", logoUrl: "/src/assets/casino-logos/stake.webp" },
    ],
  },
];
